import { describe, it, expect } from "vitest"
import { readFileSync, readdirSync, statSync } from "node:fs"
import { join } from "node:path"

/**
 * The editorial token set is declared once in `editorial-tokens.css` and then
 * MIRRORED onto every surface Radix portals outside `.editorial-surface` — the
 * date-range popover, dropdown menus, dialogs, sheets, and the mobile bottom
 * sheet. Six copies at the time of writing.
 *
 * Copies drift silently. `--ink-faint` was corrected from #a69d92 (2.48:1) to
 * clear AA, and five of the six copies kept the failing value for months:
 * every caption in a dropdown, dialog, sheet or date picker was below AA and
 * nothing said so, because each copy is valid CSS on its own.
 *
 * These tests read the stylesheets as text rather than rendering anything, so
 * they cost nothing and fail the moment a seventh copy appears out of step.
 */

const STYLE_DIR = join(process.cwd(), "src", "styles")

/**
 * `counter-components.css` is excluded, and this is a name collision rather
 * than a seventh copy. It is generated by scripts/extract-prototype-css.ts
 * from the Counter prototype, whose token names are unprefixed — `--ink`,
 * `--paper`, `--line`, `--surface` — exactly like the editorial set's, but
 * belonging to a different design system with different values. Its
 * declarations are aliases (`--ink: var(--ct-ink)`) scoped to `.ct-root` and
 * the prototype's own roots, so they are not a mirror of the editorial tokens
 * and holding them to the editorial value would be meaningless. The parity
 * this file guards — the editorial set declared once and restated on every
 * surface Radix portals outside `.editorial-surface` — is unaffected.
 *
 * That the two systems now share unprefixed names in one global stylesheet is
 * worth knowing about: it is safe today only because the selectors are
 * disjoint (no element in the app carries `ct-root`, `frame`, `pframe` or a
 * bare `login` class), and it stops being safe if an editorial surface is ever
 * nested inside a Counter root without restating its own tokens.
 */
const NOT_AN_EDITORIAL_COPY = new Set(["counter-components.css"])

function cssFiles(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => !NOT_AN_EDITORIAL_COPY.has(f))
    .map((f) => join(dir, f))
    .filter((p) => statSync(p).isFile() && p.endsWith(".css"))
}

/** Every `--token: value;` declaration in the stylesheets, with its location. */
function declarationsOf(token: string): Array<{ file: string; value: string }> {
  const out: Array<{ file: string; value: string }> = []
  for (const path of cssFiles(STYLE_DIR)) {
    const text = readFileSync(path, "utf8")
    const re = new RegExp(`^\\s*${token}:\\s*([^;]+);`, "gm")
    for (const m of text.matchAll(re)) {
      out.push({ file: path.split("/").pop()!, value: m[1].trim() })
    }
  }
  return out
}

function luminance(hex: string): number {
  const h = hex.replace("#", "")
  const parts = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const lin = parts.map((c) =>
    c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
  )
  return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]
}

function contrast(a: string, b: string): number {
  const [la, lb] = [luminance(a), luminance(b)]
  return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05)
}

/**
 * The exclusion above is only safe while the two systems' selectors are
 * disjoint, so that condition is asserted rather than described.
 *
 * `counter-components.css` styles `.ct-root`, `.frame`, `.pframe` and `.login`
 * with the Counter values of `--ink`, `--paper` and friends. Nothing in the app
 * carries any of those four as a bare class today — the login page uses
 * `login-shell`, `login-headline` and so on, and the only `frame` is
 * `m-chart-frame` — so no editorial surface can inherit a Counter token.
 *
 * WHEN THIS GOES RED: Task 3 of the Counter fidelity plan puts `ct-root` on
 * AppShell, which is a legitimate change and will fail this. Do not delete the
 * assertion to make it pass. Re-examine the exclusion instead: from that point
 * an editorial surface rendered inside the Counter root inherits `--ink` and
 * `--paper` from the alias layer unless it restates its own, and the answer is
 * either to prove no editorial surface renders there or to prefix the ported
 * token names. Narrow this list to the classes still unused, and say why.
 */
const COUNTER_ROOT_CLASSES = ["ct-root", "frame", "pframe", "login"]

function tsxFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name)
    if (e.isDirectory()) return tsxFiles(full)
    return e.isFile() && full.endsWith(".tsx") ? [full] : []
  })
}

describe("the Counter/editorial token-name collision stays harmless", () => {
  it("emits none of the Counter root classes from any component", () => {
    const offenders: string[] = []
    for (const file of tsxFiles(join(process.cwd(), "src"))) {
      const text = readFileSync(file, "utf8")
      // Every className/class value in the file, however it is written:
      // a plain attribute, a braced literal, or a cn()/clsx() argument.
      for (const m of text.matchAll(/class(?:Name)?\s*=\s*(?:"([^"]*)"|'([^']*)'|\{([\s\S]*?)\})/g)) {
        const value = m[1] ?? m[2] ?? m[3] ?? ""
        // Inside a braced expression only the string literals are class names.
        const chunks =
          m[3] === undefined
            ? [value]
            : [...value.matchAll(/["'\`]([^"'\`]*)["'\`]/g)].map((q) => q[1])
        for (const chunk of chunks) {
          for (const token of chunk.split(/[\s${}]+/)) {
            if (COUNTER_ROOT_CLASSES.includes(token)) {
              offenders.push(`${file.split("/src/")[1]}: ${token}`)
            }
          }
        }
      }
    }
    expect(offenders).toEqual([])
  })
})

describe("editorial token parity", () => {
  it("declares --ink-faint identically in every copy", () => {
    const decls = declarationsOf("--ink-faint")
    expect(decls.length, "expected several mirrored copies").toBeGreaterThan(1)
    const values = [...new Set(decls.map((d) => d.value.toLowerCase()))]
    expect(
      values,
      `--ink-faint disagrees across copies: ${decls
        .map((d) => `${d.file}=${d.value}`)
        .join(", ")}`
    ).toHaveLength(1)
  })

  it("keeps every mirrored ink token in step with the source", () => {
    // The tokens a portalled surface has to restate for the paper to resolve.
    for (const token of ["--ink", "--ink-muted", "--paper", "--hairline"]) {
      const values = [
        ...new Set(declarationsOf(token).map((d) => d.value.toLowerCase())),
      ]
      expect(values, `${token} disagrees across copies`).toHaveLength(1)
    }
  })
})

describe("caption ink clears AA across the whole page ground", () => {
  // The surface is `linear-gradient(--paper, --paper-deep)`, so a caption's
  // background depends on how far down the page it sits. Checking only against
  // --paper is what let #776d63 (4.70 at the top, 4.31 at the bottom) look
  // safe. Both ends have to pass.
  const value = () => {
    const [first] = declarationsOf("--ink-faint")
    return first.value
  }

  it("passes against the top of the gradient", () => {
    expect(contrast(value(), "#fbf6ee")).toBeGreaterThanOrEqual(4.5)
  })

  it("passes against the bottom of the gradient", () => {
    expect(contrast(value(), "#f4ecdf")).toBeGreaterThanOrEqual(4.5)
  })

  it("would have caught the value this replaced", () => {
    expect(contrast("#776d63", "#f4ecdf")).toBeLessThan(4.5)
    expect(contrast("#a69d92", "#fbf6ee")).toBeLessThan(4.5)
  })
})
