import { describe, it, expect } from "vitest"
import { readFileSync, readdirSync, statSync } from "node:fs"
import { join } from "node:path"

/**
 * The editorial token set is declared once in `editorial-tokens.css` and then
 * MIRRORED onto every surface Radix portals outside `.editorial-surface` — the
 * date-range popover, dropdown menus, dialogs, sheets, and the mobile bottom
 * sheet. Six copies at the time of writing.
 *
 * Copies drift silently. `--ink-faint` was corrected from #a69d92 (2.48:1) to
 * clear AA, and five of the six copies kept the failing value for months:
 * every caption in a dropdown, dialog, sheet or date picker was below AA and
 * nothing said so, because each copy is valid CSS on its own.
 *
 * These tests read the stylesheets as text rather than rendering anything, so
 * they cost nothing and fail the moment a seventh copy appears out of step.
 */

const STYLE_DIR = join(process.cwd(), "src", "styles")

/**
 * `counter-components.css` is excluded, and this is a name collision rather
 * than a seventh copy. It is generated by scripts/extract-prototype-css.ts
 * from the Counter prototype, whose token names are unprefixed — `--ink`,
 * `--paper`, `--line`, `--surface` — exactly like the editorial set's, but
 * belonging to a different design system with different values. Its
 * declarations are aliases (`--ink: var(--ct-ink)`) scoped to `.ct-root` and
 * the prototype's own roots, so they are not a mirror of the editorial tokens
 * and holding them to the editorial value would be meaningless. The parity
 * this file guards — the editorial set declared once and restated on every
 * surface Radix portals outside `.editorial-surface` — is unaffected.
 *
 * That the two systems now share unprefixed names in one global stylesheet is
 * worth knowing about: it is safe today only because the selectors are
 * disjoint (no element in the app carries `ct-root`, `frame`, `pframe` or a
 * bare `login` class), and it stops being safe if an editorial surface is ever
 * nested inside a Counter root without restating its own tokens.
 */
const NOT_AN_EDITORIAL_COPY = new Set(["counter-components.css"])

function cssFiles(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => !NOT_AN_EDITORIAL_COPY.has(f))
    .map((f) => join(dir, f))
    .filter((p) => statSync(p).isFile() && p.endsWith(".css"))
}

/** Every `--token: value;` declaration in the stylesheets, with its location. */
function declarationsOf(token: string): Array<{ file: string; value: string }> {
  const out: Array<{ file: string; value: string }> = []
  for (const path of cssFiles(STYLE_DIR)) {
    const text = readFileSync(path, "utf8")
    const re = new RegExp(`^\\s*${token}:\\s*([^;]+);`, "gm")
    for (const m of text.matchAll(re)) {
      out.push({ file: path.split("/").pop()!, value: m[1].trim() })
    }
  }
  return out
}

function luminance(hex: string): number {
  const h = hex.replace("#", "")
  const parts = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const lin = parts.map((c) =>
    c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
  )
  return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]
}

function contrast(a: string, b: string): number {
  const [la, lb] = [luminance(a), luminance(b)]
  return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05)
}

/**
 * The exclusion above is only safe while the two systems' selectors are
 * disjoint, so that condition is asserted rather than described.
 *
 * `counter-components.css` styles `.ct-root`, `.frame`, `.pframe` and `.login`
 * with the Counter values of `--ink`, `--paper` and friends.
 *
 * `frame`, `pframe` and `login` are still carried by nothing in the app — the
 * login page uses `login-shell`, `login-headline` and so on, and the only
 * `frame` is `m-chart-frame`. They stay banned outright.
 *
 * `ct-root` NO LONGER IS. Task 3 of the Counter fidelity plan puts it on
 * `AppShell`'s outermost element, which is what switches the ported stylesheet
 * on at all; without it the whole port applies to nothing. So the ban is
 * narrowed rather than deleted: exactly one file may emit exactly `ct-root`,
 * and `COUNTER_ROOT_EXCEPTIONS` names it.
 *
 * WHY THAT STAYS SAFE. The hazard is one specific thing — an element that
 * READS an unprefixed editorial token without restating it, rendered inside
 * `.ct-root`, where the alias layer now answers with a Counter value. That
 * requires an editorial element to be a descendant of `AppShell`, and the
 * second test below asserts that none can be:
 *
 *   1. Only `src/app/dashboard/counter-overview-client.tsx` renders
 *      `<AppShell>`. `/dashboard/page.tsx` is a sibling of the `(editorial)`
 *      route group, not a parent of it, so no editorial page nests inside it.
 *   2. The four editorial stylesheets are imported by
 *      `(editorial)/layout.tsx`, `login/layout.tsx`, `(mobile)/m/layout.tsx`,
 *      `not-found.tsx` and `shutdown/page.tsx` — none of which is on a Counter
 *      route, so on `/dashboard` those rules are not even in the document.
 *   3. Nothing in the Counter tree, or in the file that mounts it, imports
 *      Radix, `@/components/ui/**`, or an editorial stylesheet, and none of
 *      them emits an `editorial-*` class. The six mirrored token copies exist
 *      because Radix PORTALS its surfaces to `document.body`; there is no
 *      Radix under `AppShell` to portal, and nothing else there wants an
 *      editorial token.
 *
 * The day any of those three stops holding, the second test goes red before
 * the colours do. If it ever needs to hold with an editorial surface genuinely
 * nested inside a Counter root, the fix is to prefix the ported token names in
 * `scripts/extract-prototype-css.ts`, not to widen this exception.
 */
const COUNTER_ROOT_CLASSES = ["ct-root", "frame", "pframe", "login"]

/** `file suffix -> the one class it may emit`. Nothing else, nowhere else. */
const COUNTER_ROOT_EXCEPTIONS: Array<{ file: string; token: string }> = [
  { file: "components/counter/shell/app-shell.tsx", token: "ct-root" },
]

function tsxFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name)
    if (e.isDirectory()) return tsxFiles(full)
    return e.isFile() && full.endsWith(".tsx") ? [full] : []
  })
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name)
    if (e.isDirectory()) return sourceFiles(full)
    return e.isFile() && (full.endsWith(".tsx") || full.endsWith(".ts")) ? [full] : []
  })
}

describe("the Counter/editorial token-name collision stays harmless", () => {
  it("emits none of the Counter root classes, except the one file that mounts ct-root", () => {
    const offenders: string[] = []
    for (const file of tsxFiles(join(process.cwd(), "src"))) {
      const rel = file.split("/src/")[1]
      const text = readFileSync(file, "utf8")
      // Every className/class value in the file, however it is written:
      // a plain attribute, a braced literal, or a cn()/clsx() argument.
      for (const m of text.matchAll(/class(?:Name)?\s*=\s*(?:"([^"]*)"|'([^']*)'|\{([\s\S]*?)\})/g)) {
        const value = m[1] ?? m[2] ?? m[3] ?? ""
        // Inside a braced expression only the string literals are class names.
        const chunks =
          m[3] === undefined
            ? [value]
            : [...value.matchAll(/["'\`]([^"'\`]*)["'\`]/g)].map((q) => q[1])
        for (const chunk of chunks) {
          for (const token of chunk.split(/[\s${}]+/)) {
            if (!COUNTER_ROOT_CLASSES.includes(token)) continue
            const allowed = COUNTER_ROOT_EXCEPTIONS.some(
              (x) => rel === x.file && token === x.token
            )
            if (!allowed) offenders.push(`${rel}: ${token}`)
          }
        }
      }
    }
    expect(offenders).toEqual([])
  })

  it("still bans the three root classes nothing carries", () => {
    // The exception list must never quietly grow into a blanket exemption.
    expect(COUNTER_ROOT_EXCEPTIONS.map((x) => x.token)).toEqual(["ct-root"])
    expect(COUNTER_ROOT_EXCEPTIONS).toHaveLength(1)
  })

  it("keeps every editorial surface out of the Counter root", () => {
    // The three conditions from the comment above, as one sweep: the Counter
    // component tree, plus whatever file mounts <AppShell> — everything that
    // can render INSIDE .ct-root — must be free of editorial anything.
    const all = sourceFiles(join(process.cwd(), "src"))
    const mounts = all.filter((f) => /<AppShell[\s>]/.test(readFileSync(f, "utf8")))
    expect(mounts.length, "expected at least one file to mount AppShell").toBeGreaterThan(0)

    const underRoot = new Set([
      ...all.filter((f) => f.includes("/components/counter/")),
      ...mounts,
    ])

    const offenders: string[] = []
    for (const file of underRoot) {
      const text = readFileSync(file, "utf8")
      for (const [what, re] of [
        ["an editorial class", /editorial-[a-z]/],
        ["an editorial stylesheet", /@\/styles\/editorial-/],
        ["a Radix portal surface", /@radix-ui\//],
        ["a shadcn surface", /@\/components\/ui\//],
      ] as const) {
        if (re.test(text)) offenders.push(`${file.split("/src/")[1]}: ${what}`)
      }
    }
    expect(offenders).toEqual([])
  })
})

describe("editorial token parity", () => {
  it("declares --ink-faint identically in every copy", () => {
    const decls = declarationsOf("--ink-faint")
    expect(decls.length, "expected several mirrored copies").toBeGreaterThan(1)
    const values = [...new Set(decls.map((d) => d.value.toLowerCase()))]
    expect(
      values,
      `--ink-faint disagrees across copies: ${decls
        .map((d) => `${d.file}=${d.value}`)
        .join(", ")}`
    ).toHaveLength(1)
  })

  it("keeps every mirrored ink token in step with the source", () => {
    // The tokens a portalled surface has to restate for the paper to resolve.
    for (const token of ["--ink", "--ink-muted", "--paper", "--hairline"]) {
      const values = [
        ...new Set(declarationsOf(token).map((d) => d.value.toLowerCase())),
      ]
      expect(values, `${token} disagrees across copies`).toHaveLength(1)
    }
  })
})

describe("caption ink clears AA across the whole page ground", () => {
  // The surface is `linear-gradient(--paper, --paper-deep)`, so a caption's
  // background depends on how far down the page it sits. Checking only against
  // --paper is what let #776d63 (4.70 at the top, 4.31 at the bottom) look
  // safe. Both ends have to pass.
  const value = () => {
    const [first] = declarationsOf("--ink-faint")
    return first.value
  }

  it("passes against the top of the gradient", () => {
    expect(contrast(value(), "#fbf6ee")).toBeGreaterThanOrEqual(4.5)
  })

  it("passes against the bottom of the gradient", () => {
    expect(contrast(value(), "#f4ecdf")).toBeGreaterThanOrEqual(4.5)
  })

  it("would have caught the value this replaced", () => {
    expect(contrast("#776d63", "#f4ecdf")).toBeLessThan(4.5)
    expect(contrast("#a69d92", "#fbf6ee")).toBeLessThan(4.5)
  })
})
