import { describe, it, expect } from "vitest"
import { readFileSync, readdirSync, statSync } from "node:fs"
import { join } from "node:path"

/**
 * The editorial token set is declared once in `editorial-tokens.css` and then
 * MIRRORED onto every surface Radix portals outside `.editorial-surface` — the
 * date-range popover, dropdown menus, dialogs, sheets, and the mobile bottom
 * sheet. Six copies at the time of writing.
 *
 * Copies drift silently. `--ink-faint` was corrected from #a69d92 (2.48:1) to
 * clear AA, and five of the six copies kept the failing value for months:
 * every caption in a dropdown, dialog, sheet or date picker was below AA and
 * nothing said so, because each copy is valid CSS on its own.
 *
 * These tests read the stylesheets as text rather than rendering anything, so
 * they cost nothing and fail the moment a seventh copy appears out of step.
 */

const STYLE_DIR = join(process.cwd(), "src", "styles")

/**
 * `counter-components.css` is excluded, and this is a name collision rather
 * than a seventh copy. It is generated by scripts/extract-prototype-css.ts
 * from the Counter prototype, whose token names are unprefixed — `--ink`,
 * `--paper`, `--line`, `--surface` — exactly like the editorial set's, but
 * belonging to a different design system with different values. Its
 * declarations are aliases (`--ink: var(--ct-ink)`) scoped to `.ct-root` and
 * the prototype's own roots, so they are not a mirror of the editorial tokens
 * and holding them to the editorial value would be meaningless. The parity
 * this file guards — the editorial set declared once and restated on every
 * surface Radix portals outside `.editorial-surface` — is unaffected.
 *
 * That the two systems now share unprefixed names in one global stylesheet is
 * worth knowing about: it is safe today only because the selectors are
 * disjoint (no element in the app carries `ct-root`, `frame`, `pframe` or a
 * bare `login` class), and it stops being safe if an editorial surface is ever
 * nested inside a Counter root without restating its own tokens.
 */
const NOT_AN_EDITORIAL_COPY = new Set(["counter-components.css"])

function cssFiles(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => !NOT_AN_EDITORIAL_COPY.has(f))
    .map((f) => join(dir, f))
    .filter((p) => statSync(p).isFile() && p.endsWith(".css"))
}

/** Every `--token: value;` declaration in the stylesheets, with its location. */
function declarationsOf(token: string): Array<{ file: string; value: string }> {
  const out: Array<{ file: string; value: string }> = []
  for (const path of cssFiles(STYLE_DIR)) {
    const text = readFileSync(path, "utf8")
    const re = new RegExp(`^\\s*${token}:\\s*([^;]+);`, "gm")
    for (const m of text.matchAll(re)) {
      out.push({ file: path.split("/").pop()!, value: m[1].trim() })
    }
  }
  return out
}

function luminance(hex: string): number {
  const h = hex.replace("#", "")
  const parts = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const lin = parts.map((c) =>
    c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)
  )
  return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]
}

function contrast(a: string, b: string): number {
  const [la, lb] = [luminance(a), luminance(b)]
  return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05)
}

/**
 * The exclusion above is only safe while the two systems' selectors are
 * disjoint, so that condition is asserted rather than described.
 *
 * `counter-components.css` styles `.ct-root`, `.frame`, `.pframe` and `.login`
 * with the Counter values of `--ink`, `--paper` and friends.
 *
 * `frame`, `pframe` and `login` are still carried by nothing in the app — the
 * login page uses `login-shell`, `login-headline` and so on, and the only
 * `frame` is `m-chart-frame`. They stay banned outright.
 *
 * `ct-root` NO LONGER IS. Task 3 of the Counter fidelity plan puts it on
 * `AppShell`'s outermost element, which is what switches the ported stylesheet
 * on at all; without it the whole port applies to nothing. So the ban is
 * narrowed rather than deleted: exactly one file may emit exactly `ct-root`,
 * and `COUNTER_ROOT_EXCEPTIONS` names it.
 *
 * WHY THAT STAYS SAFE. The hazard is one specific thing — an element that
 * READS an unprefixed editorial token without restating it, rendered inside
 * `.ct-root`, where the alias layer now answers with a Counter value. That
 * requires an editorial element to be a descendant of `AppShell`, and the
 * second test below asserts that none can be:
 *
 *   1. Only `src/app/dashboard/counter-overview-client.tsx` renders
 *      `<AppShell>`. `/dashboard/page.tsx` is a sibling of the `(editorial)`
 *      route group, not a parent of it, so no editorial page nests inside it.
 *   2. The four editorial stylesheets are imported by
 *      `(editorial)/layout.tsx`, `login/layout.tsx`, `(mobile)/m/layout.tsx`,
 *      `not-found.tsx` and `shutdown/page.tsx`. On `/dashboard` those rules
 *      are not even in the document. On `/m` they ARE — see the third
 *      exception below — and it is still safe, because an importer of those
 *      sheets is an ANCESTOR of the Counter root, not a descendant of it, and
 *      custom properties inherit downward only.
 *   3. Nothing in the Counter tree, or in the file that mounts it, imports
 *      Radix, `@/components/ui/**`, or an editorial stylesheet, and none of
 *      them emits an `editorial-*` class. The six mirrored token copies exist
 *      because Radix PORTALS its surfaces to `document.body`; there is no
 *      Radix under `AppShell` to portal, and nothing else there wants an
 *      editorial token.
 *
 * The day any of those three stops holding, the second test goes red before
 * the colours do. If it ever needs to hold with an editorial surface genuinely
 * nested inside a Counter root, the fix is to prefix the ported token names in
 * `scripts/extract-prototype-css.ts`, not to widen this exception.
 *
 * THE SECOND EXCEPTION (task 9, the ⌘K palette). `AskSurface` PORTALS to
 * `document.body` — `.cmdkwrap` is `position:absolute;inset:0`, and both
 * `.appwrap` (`position:relative`) and `.ct-root` itself
 * (`container-type:inline-size`, which applies layout containment) would
 * otherwise be its containing block. A portal to the body lands OUTSIDE the
 * app's own `.ct-root`, where the alias layer is declared, so all 34 `.cmdk*`
 * rules would resolve `--surface`, `--line` and `--mono` to nothing. The class
 * has to travel with it, and it has to be on `.cmdkwrap` itself: a wrapping
 * `.ct-root` would be a containing block of auto height and collapse an
 * `inset:0` child to zero.
 *
 * The hazard above still does not apply, for the same reason and one more.
 * This `.ct-root` is a SIBLING of every editorial root, not an ancestor —
 * custom properties inherit downward only — and its entire subtree is the
 * palette's own ported markup: no Radix, no `@/components/ui/**`, no
 * `editorial-*` class. The third test below asserts that subtree stays that
 * way.
 *
 * THE THIRD EXCEPTION (Phase C task 4, the phone). `/m` is Counter Overview's
 * phone surface — `src/proxy.ts` redirects `/dashboard` there on a phone
 * user agent — and it is the FIRST Counter root mounted underneath a layout
 * that imports the editorial stylesheets (`(mobile)/m/layout.tsx` loads
 * `editorial-tokens.css` and `editorial-mobile.css`, and still renders the
 * editorial tab bar around the page).
 *
 * That is the nesting direction this file has always said is fine. The hazard
 * is an editorial element rendered INSIDE `.ct-root`, reading an unprefixed
 * token that the alias layer has re-answered with a Counter value. Everything
 * editorial on `/m` — the shell, the tab bar, the welcome marquee — is an
 * ancestor or a sibling of the Counter root, and custom properties do not
 * inherit upward or sideways. What is inside it is ported Counter markup and
 * nothing else, which the third test sweeps for by finding every file that
 * emits `ct-root` rather than only the ones that mount `<AppShell>`.
 */
const COUNTER_ROOT_CLASSES = ["ct-root", "ct-phone", "frame", "pframe", "login"]

/** `file suffix -> the one class it may emit`. Nothing else, nowhere else. */
const COUNTER_ROOT_EXCEPTIONS: Array<{ file: string; token: string }> = [
  // The desk frame, mounted once by `src/app/dashboard/(counter)/layout.tsx`.
  { file: "components/counter/shell/app-shell.tsx", token: "ct-root" },
  // The ⌘K palette, which portals to document.body and must carry the alias
  // layer out with it. See the note above.
  { file: "components/counter/ask/ask-surface.tsx", token: "ct-root" },
  // The PHONE frame, mounted once by `src/app/(mobile)/m/(counter)/layout.tsx`.
  // The desk's rail and topbar are not the phone's chrome, so the phone has a
  // shell of its own; it mounts the alias layer one element above `.mscroll`
  // so `.mtop` is inside it too.
  //
  // This list used to name FOUR phone islands — `/m`, `/m/pnl`, `/m/orders`
  // and `/m/orders/[id]` — because each of them opened with its own
  // `.ct-root.ct-phone`, and rebuilt the whole frame on every tab change.
  // They are one shell in one layout now, and the list is shorter for it.
  { file: "components/counter/shell/phone-shell.tsx", token: "ct-root" },
  // ...and the phone's own type scale, `.pframe`'s, worn WITH `ct-root` on
  // the same element. Listed separately because a file that emitted
  // `ct-phone` WITHOUT `ct-root` would be redeclaring the scale over the
  // desk's ink and ground, which is a defect worth failing on.
  { file: "components/counter/shell/phone-shell.tsx", token: "ct-phone" },
]

function tsxFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name)
    if (e.isDirectory()) return tsxFiles(full)
    return e.isFile() && full.endsWith(".tsx") ? [full] : []
  })
}

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = join(dir, e.name)
    if (e.isDirectory()) return sourceFiles(full)
    return e.isFile() && (full.endsWith(".tsx") || full.endsWith(".ts")) ? [full] : []
  })
}

describe("the Counter/editorial token-name collision stays harmless", () => {
  it("emits none of the Counter root classes, except the one file that mounts ct-root", () => {
    const offenders: string[] = []
    for (const file of tsxFiles(join(process.cwd(), "src"))) {
      const rel = file.split("/src/")[1]
      const text = readFileSync(file, "utf8")
      // Every className/class value in the file, however it is written:
      // a plain attribute, a braced literal, or a cn()/clsx() argument.
      for (const m of text.matchAll(/class(?:Name)?\s*=\s*(?:"([^"]*)"|'([^']*)'|\{([\s\S]*?)\})/g)) {
        const value = m[1] ?? m[2] ?? m[3] ?? ""
        // Inside a braced expression only the string literals are class names.
        const chunks =
          m[3] === undefined
            ? [value]
            : [...value.matchAll(/["'\`]([^"'\`]*)["'\`]/g)].map((q) => q[1])
        for (const chunk of chunks) {
          for (const token of chunk.split(/[\s${}]+/)) {
            if (!COUNTER_ROOT_CLASSES.includes(token)) continue
            const allowed = COUNTER_ROOT_EXCEPTIONS.some(
              (x) => rel === x.file && token === x.token
            )
            if (!allowed) offenders.push(`${rel}: ${token}`)
          }
        }
      }
    }
    expect(offenders).toEqual([])
  })

  it("still bans the three root classes nothing carries", () => {
    // The exception list must never quietly grow into a blanket exemption.
    // `frame`, `pframe` and `login` stay banned outright; the two Counter
    // roots are named file by file.
    expect(new Set(COUNTER_ROOT_EXCEPTIONS.map((x) => x.token))).toEqual(
      new Set(["ct-root", "ct-phone"]),
    )
    // Pinned, so the list cannot grow a file without someone reading this
    // note. THREE files now, down from six: the desk shell, the ⌘K palette,
    // and the phone shell — which carries both classes. The four phone
    // islands (/m, /m/pnl, /m/orders, /m/orders/[id]) each opened with their
    // own `.ct-root.ct-phone` until the chrome moved into
    // `src/app/(mobile)/m/(counter)/layout.tsx`; one shell in one layout is
    // both fewer mount sites and one that survives a tab change.
    expect(COUNTER_ROOT_EXCEPTIONS).toHaveLength(4)
    expect(new Set(COUNTER_ROOT_EXCEPTIONS.map((x) => x.file)).size).toBe(3)
    // `ct-phone` is only ever worn with `ct-root`; a file carrying it alone
    // would be redeclaring the type scale over the wrong ink and ground.
    const phone = COUNTER_ROOT_EXCEPTIONS.filter((x) => x.token === "ct-phone")
    for (const p of phone) {
      expect(COUNTER_ROOT_EXCEPTIONS).toContainEqual({ file: p.file, token: "ct-root" })
    }
  })

  it("keeps every editorial surface out of the Counter root", () => {
    // The three conditions from the comment above, as one sweep: the Counter
    // component tree, plus every file that can OPEN a .ct-root — everything
    // that can render INSIDE one — must be free of editorial anything.
    //
    // "Mounts <AppShell>" was the whole test until the phone arrived, and the
    // phone composes no AppShell: it is a Counter root under an editorial
    // layout, which is exactly the case worth sweeping. So the set is every
    // file that EMITS `ct-root`, which is the thing that actually turns the
    // alias layer on, plus the AppShell mounts that inherit it from the shell.
    const all = sourceFiles(join(process.cwd(), "src"))
    const mounts = all.filter((f) => {
      const text = readFileSync(f, "utf8")
      return /<AppShell[\s>]/.test(text) || /\bct-root\b/.test(text)
    })
    expect(mounts.length, "expected at least one file to mount AppShell").toBeGreaterThan(0)

    const underRoot = new Set([
      ...all.filter((f) => f.includes("/components/counter/")),
      ...mounts,
    ])

    const offenders: string[] = []
    for (const file of underRoot) {
      const text = readFileSync(file, "utf8")
      for (const [what, re] of [
        ["an editorial class", /editorial-[a-z]/],
        ["an editorial stylesheet", /@\/styles\/editorial-/],
        ["a Radix portal surface", /@radix-ui\//],
        ["a shadcn surface", /@\/components\/ui\//],
      ] as const) {
        if (re.test(text)) offenders.push(`${file.split("/src/")[1]}: ${what}`)
      }
    }
    expect(offenders).toEqual([])
  })
})

describe("editorial token parity", () => {
  it("declares --ink-faint identically in every copy", () => {
    const decls = declarationsOf("--ink-faint")
    expect(decls.length, "expected several mirrored copies").toBeGreaterThan(1)
    const values = [...new Set(decls.map((d) => d.value.toLowerCase()))]
    expect(
      values,
      `--ink-faint disagrees across copies: ${decls
        .map((d) => `${d.file}=${d.value}`)
        .join(", ")}`
    ).toHaveLength(1)
  })

  it("keeps every mirrored ink token in step with the source", () => {
    // The tokens a portalled surface has to restate for the paper to resolve.
    for (const token of ["--ink", "--ink-muted", "--paper", "--hairline"]) {
      const values = [
        ...new Set(declarationsOf(token).map((d) => d.value.toLowerCase())),
      ]
      expect(values, `${token} disagrees across copies`).toHaveLength(1)
    }
  })
})

describe("caption ink clears AA across the whole page ground", () => {
  // The surface is `linear-gradient(--paper, --paper-deep)`, so a caption's
  // background depends on how far down the page it sits. Checking only against
  // --paper is what let #776d63 (4.70 at the top, 4.31 at the bottom) look
  // safe. Both ends have to pass.
  const value = () => {
    const [first] = declarationsOf("--ink-faint")
    return first.value
  }

  it("passes against the top of the gradient", () => {
    expect(contrast(value(), "#fbf6ee")).toBeGreaterThanOrEqual(4.5)
  })

  it("passes against the bottom of the gradient", () => {
    expect(contrast(value(), "#f4ecdf")).toBeGreaterThanOrEqual(4.5)
  })

  it("would have caught the value this replaced", () => {
    expect(contrast("#776d63", "#f4ecdf")).toBeLessThan(4.5)
    expect(contrast("#a69d92", "#fbf6ee")).toBeLessThan(4.5)
  })
})
