/**
 * Every page in the prototype, and where it stands in this project.
 *
 * This doubles as the progress board. `npm run fidelity` prints one line per
 * page, so the suite is a live count of how much of the design is genuinely
 * built rather than a claim in a plan. A page flips to "counter" in the same
 * commit that rebuilds it, which makes it impossible to call a page done
 * without turning its own gate on.
 *
 * The 53 rows below were generated by walking the prototype's own page index
 * (`.pchip[data-goto]`) — they are its ids, its names and its own route
 * strings, not a hand-typed list.
 */
export type PageStatus = "counter" | "editorial"

export interface FidelityPage {
  /** The prototype's own page module id, e.g. "overview". */
  protoId: string
  /** The prototype's name for it, for report headings. */
  name: string
  /**
   * The route the PROTOTYPE prints for this page. `openPrototype` asserts
   * against it, which is how a navigation that silently did not happen is
   * caught before anything is compared.
   */
  protoRoute: string
  /**
   * OUR route. For an "editorial" page this is a claim copied from the
   * prototype, not a verified route — it is checked the day the page flips to
   * "counter" and the suite actually visits it.
   */
  route: string
  /**
   * Where the mobile projects actually land after asking for `route`. The
   * middleware rewrites /dashboard/* to /m/*, and the fidelity suite asserts
   * the landed path so that a 404 or a guard redirect is reported as a page
   * that did not load rather than as a design difference. Omit it when the
   * mobile projects land on `route` unchanged.
   */
  mobileRoute?: string
  /** "editorial" pages are not rebuilt yet and are SKIPPED, not failed. */
  status: PageStatus
  /**
   * Capture and commit a report for this page even while it is still
   * "editorial" — captured, never gated.
   *
   * Overview carries it, and only Overview. It is the page that proved the
   * problem, and the addendum measures this whole project against its
   * "before". Marking it "counter" instead would have made `npm run fidelity`
   * red from the first commit, and a permanently red gate is exactly as
   * ignorable as the permanently green one that let this happen.
   */
  report?: boolean
  /**
   * Landmark counts on the day the page first passed. A later run finding
   * fewer is a silent regression, not a pass. Set it when the page goes green.
   */
  baseline?: { desktop: number; mobile: number }
}

export const PAGES: FidelityPage[] = [
  { protoId: "overview", name: "Overview", protoRoute: "/dashboard", route: "/dashboard", mobileRoute: "/m", status: "editorial", report: true },
  { protoId: "ask", name: "Ask", protoRoute: "/dashboard/chat", route: "/dashboard/chat", status: "editorial" },
  { protoId: "decisions", name: "Needs you", protoRoute: "/dashboard/decisions", route: "/dashboard/decisions", status: "editorial" },
  { protoId: "alerts", name: "Needs you", protoRoute: "/dashboard/alerts", route: "/dashboard/alerts", status: "editorial" },
  { protoId: "orders", name: "Orders", protoRoute: "/dashboard/orders", route: "/dashboard/orders", status: "editorial" },
  { protoId: "order", name: "An order", protoRoute: "/dashboard/orders/4821", route: "/dashboard/orders/4821", status: "editorial" },
  { protoId: "analytics", name: "Analytics", protoRoute: "/dashboard/analytics", route: "/dashboard/analytics", status: "editorial" },
  { protoId: "pnl", name: "P&L", protoRoute: "/dashboard/pnl", route: "/dashboard/pnl", status: "editorial" },
  { protoId: "cogs", name: "COGS", protoRoute: "/dashboard/cogs", route: "/dashboard/cogs", status: "editorial" },
  { protoId: "menu", name: "Menu profit", protoRoute: "/dashboard/menu-profit", route: "/dashboard/menu-profit", status: "editorial" },
  { protoId: "labor", name: "Labor", protoRoute: "/dashboard/labor", route: "/dashboard/labor", status: "editorial" },
  { protoId: "pnlstore", name: "P&L", protoRoute: "/dashboard/pnl/hollywood", route: "/dashboard/pnl/hollywood", status: "editorial" },
  { protoId: "menuhub", name: "Menu profit", protoRoute: "/dashboard/menu", route: "/dashboard/menu", status: "editorial" },
  { protoId: "catalog", name: "Menu profit", protoRoute: "/dashboard/menu/catalog", route: "/dashboard/menu/catalog", status: "editorial" },
  { protoId: "catalogitem", name: "A menu item", protoRoute: "/dashboard/menu/catalog/neddy-burger", route: "/dashboard/menu/catalog/neddy-burger", status: "editorial" },
  { protoId: "recipes", name: "Recipes", protoRoute: "/dashboard/recipes", route: "/dashboard/recipes", status: "editorial" },
  { protoId: "recipe", name: "Recipe", protoRoute: "/dashboard/recipes/double-slider", route: "/dashboard/recipes/double-slider", status: "editorial" },
  { protoId: "productmix", name: "Menu profit", protoRoute: "/dashboard/product-mix", route: "/dashboard/product-mix", status: "editorial" },
  { protoId: "usage", name: "COGS", protoRoute: "/dashboard/operations/product-usage", route: "/dashboard/operations/product-usage", status: "editorial" },
  { protoId: "operations", name: "Operations", protoRoute: "/dashboard/operations", route: "/dashboard/operations", status: "editorial" },
  { protoId: "invoices", name: "Invoices", protoRoute: "/dashboard/invoices", route: "/dashboard/invoices", status: "editorial" },
  { protoId: "invoice", name: "An invoice", protoRoute: "/dashboard/invoices/I28517", route: "/dashboard/invoices/I28517", status: "editorial" },
  { protoId: "inventory", name: "Inventory", protoRoute: "/dashboard/operations/inventory", route: "/dashboard/operations/inventory", status: "editorial" },
  { protoId: "countnew", name: "Inventory", protoRoute: "/dashboard/operations/inventory/count/new", route: "/dashboard/operations/inventory/count/new", status: "editorial" },
  { protoId: "counts", name: "Inventory", protoRoute: "/dashboard/operations/inventory/counts", route: "/dashboard/operations/inventory/counts", status: "editorial" },
  { protoId: "countsession", name: "A count", protoRoute: "/dashboard/operations/inventory/counts/aug-14", route: "/dashboard/operations/inventory/counts/aug-14", status: "editorial" },
  { protoId: "ingredients", name: "Ingredients", protoRoute: "/dashboard/ingredients", route: "/dashboard/ingredients", status: "editorial" },
  { protoId: "ingredient", name: "An ingredient", protoRoute: "/dashboard/ingredients/ground-beef-80-20", route: "/dashboard/ingredients/ground-beef-80-20", status: "editorial" },
  { protoId: "prices", name: "Ingredients", protoRoute: "/dashboard/ingredients/prices", route: "/dashboard/ingredients/prices", status: "editorial" },
  { protoId: "vendors", name: "Vendors", protoRoute: "/dashboard/operations/vendors", route: "/dashboard/operations/vendors", status: "editorial" },
  { protoId: "vendor", name: "A vendor", protoRoute: "/dashboard/operations/vendors/ifs-produce", route: "/dashboard/operations/vendors/ifs-produce", status: "editorial" },
  { protoId: "packaging", name: "Vendors", protoRoute: "/dashboard/operations/packaging", route: "/dashboard/operations/packaging", status: "editorial" },
  { protoId: "stores", name: "Stores", protoRoute: "/dashboard/stores", route: "/dashboard/stores", status: "editorial" },
  { protoId: "storecosts", name: "Stores", protoRoute: "/dashboard/stores/hollywood", route: "/dashboard/stores/hollywood", status: "editorial" },
  { protoId: "storeedit", name: "Stores", protoRoute: "/dashboard/stores/new", route: "/dashboard/stores/new", status: "editorial" },
  { protoId: "settings", name: "Settings", protoRoute: "/dashboard/settings", route: "/dashboard/settings", status: "editorial" },
  { protoId: "more", name: "More (phone)", protoRoute: "/m/more", route: "/m/more", status: "editorial" },
  { protoId: "monitoring", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring", route: "/dashboard/admin/monitoring", status: "editorial" },
  { protoId: "monml", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ml", route: "/dashboard/admin/monitoring/ml", status: "editorial" },
  { protoId: "monpeople", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/people", route: "/dashboard/admin/monitoring/people", status: "editorial" },
  { protoId: "analyticsstore", name: "Analytics", protoRoute: "/dashboard/analytics/hollywood", route: "/dashboard/analytics/hollywood", status: "editorial" },
  { protoId: "laborstore", name: "Labor", protoRoute: "/dashboard/labor/hollywood", route: "/dashboard/labor/hollywood", status: "editorial" },
  { protoId: "cogsstore", name: "COGS", protoRoute: "/dashboard/cogs/hollywood", route: "/dashboard/cogs/hollywood", status: "editorial" },
  { protoId: "moninfra", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/infrastructure", route: "/dashboard/admin/monitoring/infrastructure", status: "editorial" },
  { protoId: "moncosts", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/costs", route: "/dashboard/admin/monitoring/costs", status: "editorial" },
  { protoId: "moncache", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/cache", route: "/dashboard/admin/monitoring/cache", status: "editorial" },
  { protoId: "monactivity", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/activity", route: "/dashboard/admin/monitoring/activity", status: "editorial" },
  { protoId: "moningredients", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ingredient-audit", route: "/dashboard/admin/monitoring/ingredient-audit", status: "editorial" },
  { protoId: "login", name: "Login", protoRoute: "/login", route: "/login", status: "editorial" },
  { protoId: "signup", name: "Accept invite", protoRoute: "/signup/[token]", route: "/signup/[token]", status: "editorial" },
  { protoId: "shutdown", name: "Shutdown", protoRoute: "/shutdown", route: "/shutdown", status: "editorial" },
  { protoId: "notfound", name: "Not found", protoRoute: "/dashboard/not-found", route: "/dashboard/not-found", status: "editorial" },
  { protoId: "forbidden", name: "No access", protoRoute: "403", route: "403", status: "editorial" },
]

export function pageById(protoId: string): FidelityPage {
  const p = PAGES.find((x) => x.protoId === protoId)
  if (!p) throw new Error(`No fidelity manifest entry for "${protoId}"`)
  return p
}

