/**
 * Every page in the prototype, and where it stands in this project.
 *
 * This doubles as the progress board. `npm run fidelity` prints one line per
 * page, so the suite is a live count of how much of the design is genuinely
 * built rather than a claim in a plan. A page flips to "counter" in the same
 * commit that rebuilds it, which makes it impossible to call a page done
 * without turning its own gate on.
 *
 * The 53 rows below were generated by walking the prototype's own page index
 * (`.pchip[data-goto]`) — they are its ids, its names and its own route
 * strings, not a hand-typed list.
 */
export type PageStatus = "counter" | "editorial"

interface FidelityPageBase {
  /** The prototype's own page module id, e.g. "overview". */
  protoId: string
  /** The prototype's name for it, for report headings. */
  name: string
  /**
   * The route the PROTOTYPE prints for this page. `openPrototype` asserts
   * against it, which is how a navigation that silently did not happen is
   * caught before anything is compared.
   */
  protoRoute: string
  /**
   * OUR route. For an "editorial" page this is a claim copied from the
   * prototype, not a verified route — it is checked the day the page flips to
   * "counter" and the suite actually visits it.
   */
  route: string
  /**
   * The query string the suite asks for, appended to `route`.
   *
   * WHY A PAGE NEEDS ONE. The prototype renders every page in ONE window: its
   * date control opens at `preset:'d7', cmp:'weekday'` (line 1757) and it has
   * no database, so a seven-day series is what every chart on every page is
   * drawn from. Our default is `yesterday` — one day, deliberately (an owner
   * opening the dashboard in the morning wants the day that finished). One
   * reading is not a chart, so `Chart` degrades it to `.strip strip--fit`,
   * which is EXACTLY what the prototype's own `chart()` does at line 3140
   * with the same input.
   *
   * Compared without this, that agreement reads as a difference: the gate
   * reports a missing `.ch` and an extra `.strip` for a rule behaving
   * identically on both sides — and an extra silently leaves the rendering
   * comparison (ruling F-R8), shrinking what is checked. So the suite asks
   * for the window the prototype is in, and the two answer the same question.
   *
   * This is ruling C-R5's fix one layer up: there the prototype's frame was
   * widened to our viewport so `@container fr` resolved against the same
   * width on both sides; here the range is matched so the SERIES has the same
   * shape. Both are the harness removing a difference it introduced itself.
   *
   * It is NOT a way to dodge a real gap. It sets the reader's window and
   * nothing else — every figure still comes from the database, and a page
   * that renders differently at its own default is still rendering
   * differently at its own default.
   */
  query?: string
  /**
   * Where the mobile projects actually land after asking for `route`. The
   * middleware rewrites /dashboard/* to /m/*, and the fidelity suite asserts
   * the landed path so that a 404 or a guard redirect is reported as a page
   * that did not load rather than as a design difference. Omit it when the
   * mobile projects land on `route` unchanged.
   */
  mobileRoute?: string
  /** "editorial" pages are not rebuilt yet and are SKIPPED, not failed. */
  status: PageStatus
  /**
   * Capture and commit a report for this page even while it is still
   * "editorial" — captured, never gated.
   *
   * Overview carries it, and only Overview. It is the page that proved the
   * problem, and the addendum measures this whole project against its
   * "before". Marking it "counter" instead would have made `npm run fidelity`
   * red from the first commit, and a permanently red gate is exactly as
   * ignorable as the permanently green one that let this happen.
   */
  report?: boolean
  /**
   * Named contrast exceptions, for elements the 4.5:1 rule flags but which are
   * genuinely fine (ruling F-R6). The threshold NEVER moves — an exception is
   * a reviewable line naming the element and the ratio it actually measures,
   * the same pattern `src/styles/counter.css` already uses for its documented
   * WCAG exceptions. A lowered threshold would silently forgive every element
   * on the page; this forgives exactly one, in writing, with its number.
   */
  contrastAllowances?: Array<{ selector: string; reason: string; measured: number }>
  /**
   * Landmarks the prototype renders that this page CANNOT, because nothing in
   * the database publishes what they would say — with the count, per surface,
   * and the reason.
   *
   * Ruling Scan-R1: a figure judged against nothing gets no meter. The
   * prototype draws a bullet under all six of Overview's strip figures because
   * it invented six thresholds; this schema publishes exactly two
   * (`Store.targetCogsPct`, and prime cost's trade ceiling under C-R1), so
   * four of those figures carry no `Reference` and therefore no `.blt`, no
   * `.band` and no `.sp`. The page is right and the schema is the follow-up.
   * Inventing a threshold to close the gate would put a number on the screen
   * that nobody set, judging an owner's business against it.
   *
   * THIS IS NOT A TOLERANCE, and the three rules in
   * `applyAbsenceAllowances` are why:
   *
   *   - it forgives an exact COUNT, so one more missing meter than recorded is
   *     still a failure;
   *   - it never forgives an EXTRA (ruling F-R8);
   *   - and an allowance that forgives FEWER than it budgets for fails as
   *     stale — the day a target is published the landmark lands, and the line
   *     saying it cannot has to go, or it would silently absorb a real
   *     regression later.
   *
   * Every entry names the function that would have produced the landmark and
   * the thing it has no input for. If you cannot write that sentence, the
   * landmark is missing because the page is unfinished, and this is the wrong
   * place for it.
   */
  absentLandmarks?: Array<{
    /** The landmark's full class list, sorted and dot-joined — `signature()`'s key. */
    landmark: string
    desktop: number
    mobile: number
    reason: string
  }>
}

/**
 * A page is either not rebuilt yet, or it is rebuilt AND carries the landmark
 * counts it passed with.
 *
 * `baseline` is required on a "counter" page and forbidden on an "editorial"
 * one, so a page cannot be declared done without acquiring a regression floor
 * in the same edit (ruling F-R4). A later run finding fewer landmarks than the
 * baseline is a silent regression, not a pass.
 *
 * This is a type rather than a lint because `npm run fidelity` needs a running
 * server and so cannot join `npm test`. The manifest carries the weight
 * instead: marking a page done without a floor fails `tsc`, which every gate
 * already runs.
 */
export type FidelityPage =
  | (FidelityPageBase & { status: "editorial"; baseline?: never })
  | (FidelityPageBase & {
      status: "counter"
      baseline: { desktop: number; mobile: number }
    })

export const PAGES: FidelityPage[] = [
  {
    protoId: "overview",
    name: "Overview",
    protoRoute: "/dashboard",
    route: "/dashboard",
    query: "?range=d7&cmp=weekday",
    mobileRoute: "/m",
    status: "counter",
    report: true,
    baseline: { desktop: 76, mobile: 44 },
    absentLandmarks: [
      {
        landmark: "blt",
        desktop: 5,
        mobile: 4,
        reason:
          "The bullet meter. `Figure` draws it from a `Reference`, and " +
          "`referenceFor` in the Overview adapter returns undefined when no " +
          "target is published. This schema publishes two: " +
          "`Store.targetCogsPct` (food cost) and prime cost's trade ceiling " +
          "(PRIME_CEILING_PCT, ruling C-R1). Orders, avg ticket, labour and " +
          "marketplace fees are judged against nothing at all — the " +
          "prototype's bands for them are its own invention (`ords * 0.92`, " +
          "`$25.10-$26.40`), which is the figure judging itself. The desk " +
          "also loses the SPLH lead figure's meter for the same reason; the " +
          "phone does not draw that figure. Ruling Scan-R1.",
      },
      {
        landmark: "band",
        desktop: 2,
        mobile: 3,
        reason:
          "The flag words under a figure, which say what it was judged " +
          "against. `Figure` opens the band on `caption || reference`, so a " +
          "figure with neither has none — the same four unjudged figures as " +
          "`blt` above, minus the two the adapter gives a caption to on their " +
          "own (`Plan 28.5%` on food cost, `excludes grubhub` on fees). The " +
          "phone loses one more than the desk because `MStrip` follows " +
          "`mstrip()` and opens its band only inside the reference branch.",
      },
      {
        landmark: "hfloor",
        desktop: 1,
        mobile: 0,
        reason:
          "The floor meter under sales per labour hour. Nothing in this " +
          "schema publishes an SPLH floor: the prototype's `SPLH_FLOOR = " +
          "68.00` is its own number, and `SplhPoint.targetSplh` is the " +
          "median of the store's own weekday history — the figure judging " +
          "itself. `FloorMeter` mounts only when a floor is published, so " +
          "today it does not mount. The phone's head block carries one figure " +
          "and it is net sales, so this landmark is not on that surface at all.",
      },
      {
        landmark: "sp",
        desktop: 1,
        mobile: 0,
        reason:
          "The sparkline. `Figure` draws it from `reference.series`, so a " +
          "figure with no reference has no series to draw — downstream of the " +
          "same missing target as `blt`. The phone draws no sparklines at " +
          "all, by the prototype's own decision (`mstrip()`: the two charts " +
          "are directly beneath and vertical space is the scarce thing), so " +
          "neither side has one there and nothing is missing.",
      },
      {
        landmark: "moneyline",
        desktop: 1,
        mobile: 0,
        reason:
          "The invoices tile's fourth line, \"Does not reconcile\". " +
          "`Invoice` does carry `reviewReasons` — the `ReviewReason[]` " +
          "`src/lib/invoice-sanity.ts` writes when a header total does not " +
          "match its lines — but `getInvoiceSummary` neither selects nor " +
          "aggregates it, and no other existing function does. Three real " +
          "lines rather than four with one guessed. The phone drops the " +
          "invoices tile entirely, as the prototype's phone does.",
      },
    ],
  },
  { protoId: "ask", name: "Ask", protoRoute: "/dashboard/chat", route: "/dashboard/chat", status: "editorial" },
  { protoId: "decisions", name: "Needs you", protoRoute: "/dashboard/decisions", route: "/dashboard/decisions", status: "editorial" },
  { protoId: "alerts", name: "Needs you", protoRoute: "/dashboard/alerts", route: "/dashboard/alerts", status: "editorial" },
  { protoId: "orders", name: "Orders", protoRoute: "/dashboard/orders", route: "/dashboard/orders", status: "editorial" },
  { protoId: "order", name: "An order", protoRoute: "/dashboard/orders/4821", route: "/dashboard/orders/4821", status: "editorial" },
  { protoId: "analytics", name: "Analytics", protoRoute: "/dashboard/analytics", route: "/dashboard/analytics", status: "editorial" },
  {
    protoId: "pnl",
    name: "P&L",
    protoRoute: "/dashboard/pnl",
    route: "/dashboard/pnl",
    // The window the prototype is in — same as Overview's, and for the same
    // reason (see `query` above). Our default is one day; a statement drawn
    // over one day degrades every series on it, and the gate would report that
    // agreement as a difference.
    query: "?range=d7&cmp=weekday",
    // The middleware rewrites /dashboard/pnl to /m/pnl on a phone UA, so the
    // mobile projects land there. Stated so a rewrite is not reported as a
    // page that failed to load. The phone SURFACE is still editorial — that is
    // Task 5 — and its report says so in landmark counts.
    mobileRoute: "/m/pnl",
    // Rebuilt on Counter in Phase C task 4 and MEASURED from that commit, but
    // still `editorial` — captured, never gated. Task 6 turns it into a gate,
    // with a baseline and the written `absentLandmarks` that say which of the
    // prototype's landmarks this schema cannot produce. Reporting first and
    // gating second is the order Overview went in: a baseline invented before
    // it was measured is a number nobody can defend.
    report: true,
    status: "editorial",
  },
  { protoId: "cogs", name: "COGS", protoRoute: "/dashboard/cogs", route: "/dashboard/cogs", status: "editorial" },
  { protoId: "menu", name: "Menu profit", protoRoute: "/dashboard/menu-profit", route: "/dashboard/menu-profit", status: "editorial" },
  { protoId: "labor", name: "Labor", protoRoute: "/dashboard/labor", route: "/dashboard/labor", status: "editorial" },
  { protoId: "pnlstore", name: "P&L", protoRoute: "/dashboard/pnl/hollywood", route: "/dashboard/pnl/hollywood", status: "editorial" },
  { protoId: "menuhub", name: "Menu profit", protoRoute: "/dashboard/menu", route: "/dashboard/menu", status: "editorial" },
  { protoId: "catalog", name: "Menu profit", protoRoute: "/dashboard/menu/catalog", route: "/dashboard/menu/catalog", status: "editorial" },
  { protoId: "catalogitem", name: "A menu item", protoRoute: "/dashboard/menu/catalog/neddy-burger", route: "/dashboard/menu/catalog/neddy-burger", status: "editorial" },
  { protoId: "recipes", name: "Recipes", protoRoute: "/dashboard/recipes", route: "/dashboard/recipes", status: "editorial" },
  { protoId: "recipe", name: "Recipe", protoRoute: "/dashboard/recipes/double-slider", route: "/dashboard/recipes/double-slider", status: "editorial" },
  { protoId: "productmix", name: "Menu profit", protoRoute: "/dashboard/product-mix", route: "/dashboard/product-mix", status: "editorial" },
  { protoId: "usage", name: "COGS", protoRoute: "/dashboard/operations/product-usage", route: "/dashboard/operations/product-usage", status: "editorial" },
  { protoId: "operations", name: "Operations", protoRoute: "/dashboard/operations", route: "/dashboard/operations", status: "editorial" },
  { protoId: "invoices", name: "Invoices", protoRoute: "/dashboard/invoices", route: "/dashboard/invoices", status: "editorial" },
  { protoId: "invoice", name: "An invoice", protoRoute: "/dashboard/invoices/I28517", route: "/dashboard/invoices/I28517", status: "editorial" },
  { protoId: "inventory", name: "Inventory", protoRoute: "/dashboard/operations/inventory", route: "/dashboard/operations/inventory", status: "editorial" },
  { protoId: "countnew", name: "Inventory", protoRoute: "/dashboard/operations/inventory/count/new", route: "/dashboard/operations/inventory/count/new", status: "editorial" },
  { protoId: "counts", name: "Inventory", protoRoute: "/dashboard/operations/inventory/counts", route: "/dashboard/operations/inventory/counts", status: "editorial" },
  { protoId: "countsession", name: "A count", protoRoute: "/dashboard/operations/inventory/counts/aug-14", route: "/dashboard/operations/inventory/counts/aug-14", status: "editorial" },
  { protoId: "ingredients", name: "Ingredients", protoRoute: "/dashboard/ingredients", route: "/dashboard/ingredients", status: "editorial" },
  { protoId: "ingredient", name: "An ingredient", protoRoute: "/dashboard/ingredients/ground-beef-80-20", route: "/dashboard/ingredients/ground-beef-80-20", status: "editorial" },
  { protoId: "prices", name: "Ingredients", protoRoute: "/dashboard/ingredients/prices", route: "/dashboard/ingredients/prices", status: "editorial" },
  { protoId: "vendors", name: "Vendors", protoRoute: "/dashboard/operations/vendors", route: "/dashboard/operations/vendors", status: "editorial" },
  { protoId: "vendor", name: "A vendor", protoRoute: "/dashboard/operations/vendors/ifs-produce", route: "/dashboard/operations/vendors/ifs-produce", status: "editorial" },
  { protoId: "packaging", name: "Vendors", protoRoute: "/dashboard/operations/packaging", route: "/dashboard/operations/packaging", status: "editorial" },
  { protoId: "stores", name: "Stores", protoRoute: "/dashboard/stores", route: "/dashboard/stores", status: "editorial" },
  { protoId: "storecosts", name: "Stores", protoRoute: "/dashboard/stores/hollywood", route: "/dashboard/stores/hollywood", status: "editorial" },
  { protoId: "storeedit", name: "Stores", protoRoute: "/dashboard/stores/new", route: "/dashboard/stores/new", status: "editorial" },
  { protoId: "settings", name: "Settings", protoRoute: "/dashboard/settings", route: "/dashboard/settings", status: "editorial" },
  { protoId: "more", name: "More (phone)", protoRoute: "/m/more", route: "/m/more", status: "editorial" },
  { protoId: "monitoring", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring", route: "/dashboard/admin/monitoring", status: "editorial" },
  { protoId: "monml", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ml", route: "/dashboard/admin/monitoring/ml", status: "editorial" },
  { protoId: "monpeople", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/people", route: "/dashboard/admin/monitoring/people", status: "editorial" },
  { protoId: "analyticsstore", name: "Analytics", protoRoute: "/dashboard/analytics/hollywood", route: "/dashboard/analytics/hollywood", status: "editorial" },
  { protoId: "laborstore", name: "Labor", protoRoute: "/dashboard/labor/hollywood", route: "/dashboard/labor/hollywood", status: "editorial" },
  { protoId: "cogsstore", name: "COGS", protoRoute: "/dashboard/cogs/hollywood", route: "/dashboard/cogs/hollywood", status: "editorial" },
  { protoId: "moninfra", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/infrastructure", route: "/dashboard/admin/monitoring/infrastructure", status: "editorial" },
  { protoId: "moncosts", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/costs", route: "/dashboard/admin/monitoring/costs", status: "editorial" },
  { protoId: "moncache", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/cache", route: "/dashboard/admin/monitoring/cache", status: "editorial" },
  { protoId: "monactivity", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/activity", route: "/dashboard/admin/monitoring/activity", status: "editorial" },
  { protoId: "moningredients", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ingredient-audit", route: "/dashboard/admin/monitoring/ingredient-audit", status: "editorial" },
  { protoId: "login", name: "Login", protoRoute: "/login", route: "/login", status: "editorial" },
  { protoId: "signup", name: "Accept invite", protoRoute: "/signup/[token]", route: "/signup/[token]", status: "editorial" },
  { protoId: "shutdown", name: "Shutdown", protoRoute: "/shutdown", route: "/shutdown", status: "editorial" },
  { protoId: "notfound", name: "Not found", protoRoute: "/dashboard/not-found", route: "/dashboard/not-found", status: "editorial" },
  { protoId: "forbidden", name: "No access", protoRoute: "403", route: "403", status: "editorial" },
]

/** The absence budget for one surface, as `applyAbsenceAllowances` wants it. */
export function absenceBudget(
  entry: FidelityPage,
  surface: "desk" | "phone",
): Record<string, number> {
  const out: Record<string, number> = {}
  for (const a of entry.absentLandmarks ?? []) {
    const n = surface === "desk" ? a.desktop : a.mobile
    if (n > 0) out[a.landmark] = n
  }
  return out
}

export function pageById(protoId: string): FidelityPage {
  const p = PAGES.find((x) => x.protoId === protoId)
  if (!p) throw new Error(`No fidelity manifest entry for "${protoId}"`)
  return p
}

