/**
 * Every page in the prototype, and where it stands in this project.
 *
 * This doubles as the progress board. `npm run fidelity` prints one line per
 * page, so the suite is a live count of how much of the design is genuinely
 * built rather than a claim in a plan. A page flips to "counter" in the same
 * commit that rebuilds it, which makes it impossible to call a page done
 * without turning its own gate on.
 *
 * The 53 rows below were generated by walking the prototype's own page index
 * (`.pchip[data-goto]`) — they are its ids, its names and its own route
 * strings, not a hand-typed list.
 */
export type PageStatus = "counter" | "editorial"

interface FidelityPageBase {
  /** The prototype's own page module id, e.g. "overview". */
  protoId: string
  /** The prototype's name for it, for report headings. */
  name: string
  /**
   * The route the PROTOTYPE prints for this page. `openPrototype` asserts
   * against it, which is how a navigation that silently did not happen is
   * caught before anything is compared.
   */
  protoRoute: string
  /**
   * OUR route. For an "editorial" page this is a claim copied from the
   * prototype, not a verified route — it is checked the day the page flips to
   * "counter" and the suite actually visits it.
   */
  route: string
  /**
   * The query string the suite asks for, appended to `route`.
   *
   * WHY A PAGE NEEDS ONE. The prototype renders every page in ONE window: its
   * date control opens at `preset:'d7', cmp:'weekday'` (line 1757) and it has
   * no database, so a seven-day series is what every chart on every page is
   * drawn from. Our default is `yesterday` — one day, deliberately (an owner
   * opening the dashboard in the morning wants the day that finished). One
   * reading is not a chart, so `Chart` degrades it to `.strip strip--fit`,
   * which is EXACTLY what the prototype's own `chart()` does at line 3140
   * with the same input.
   *
   * Compared without this, that agreement reads as a difference: the gate
   * reports a missing `.ch` and an extra `.strip` for a rule behaving
   * identically on both sides — and an extra silently leaves the rendering
   * comparison (ruling F-R8), shrinking what is checked. So the suite asks
   * for the window the prototype is in, and the two answer the same question.
   *
   * This is ruling C-R5's fix one layer up: there the prototype's frame was
   * widened to our viewport so `@container fr` resolved against the same
   * width on both sides; here the range is matched so the SERIES has the same
   * shape. Both are the harness removing a difference it introduced itself.
   *
   * It is NOT a way to dodge a real gap. It sets the reader's window and
   * nothing else — every figure still comes from the database, and a page
   * that renders differently at its own default is still rendering
   * differently at its own default.
   */
  query?: string
  /**
   * Where the mobile projects actually land after asking for `route`. The
   * middleware rewrites /dashboard/* to /m/*, and the fidelity suite asserts
   * the landed path so that a 404 or a guard redirect is reported as a page
   * that did not load rather than as a design difference. Omit it when the
   * mobile projects land on `route` unchanged.
   */
  mobileRoute?: string
  /** "editorial" pages are not rebuilt yet and are SKIPPED, not failed. */
  status: PageStatus
  /**
   * Capture and commit a report for this page even while it is still
   * "editorial" — captured, never gated.
   *
   * Overview carries it, and only Overview. It is the page that proved the
   * problem, and the addendum measures this whole project against its
   * "before". Marking it "counter" instead would have made `npm run fidelity`
   * red from the first commit, and a permanently red gate is exactly as
   * ignorable as the permanently green one that let this happen.
   */
  report?: boolean
  /**
   * Named contrast exceptions, for elements the 4.5:1 rule flags but which are
   * genuinely fine (ruling F-R6). The threshold NEVER moves — an exception is
   * a reviewable line naming the element and the ratio it actually measures,
   * the same pattern `src/styles/counter.css` already uses for its documented
   * WCAG exceptions. A lowered threshold would silently forgive every element
   * on the page; this forgives exactly one, in writing, with its number.
   */
  contrastAllowances?: Array<{ selector: string; reason: string; measured: number }>
  /**
   * Landmarks the prototype renders that this page CANNOT, because nothing in
   * the database publishes what they would say — with the count, per surface,
   * and the reason.
   *
   * Ruling Scan-R1: a figure judged against nothing gets no meter. The
   * prototype draws a bullet under all six of Overview's strip figures because
   * it invented six thresholds; this schema publishes exactly two
   * (`Store.targetCogsPct`, and prime cost's trade ceiling under C-R1), so
   * four of those figures carry no `Reference` and therefore no `.blt`, no
   * `.band` and no `.sp`. The page is right and the schema is the follow-up.
   * Inventing a threshold to close the gate would put a number on the screen
   * that nobody set, judging an owner's business against it.
   *
   * THIS IS NOT A TOLERANCE, and the three rules in
   * `applyAbsenceAllowances` are why:
   *
   *   - it forgives an exact COUNT, so one more missing meter than recorded is
   *     still a failure;
   *   - it never forgives an EXTRA (ruling F-R8);
   *   - and an allowance that forgives FEWER than it budgets for fails as
   *     stale — the day a target is published the landmark lands, and the line
   *     saying it cannot has to go, or it would silently absorb a real
   *     regression later.
   *
   * Every entry names the function that would have produced the landmark and
   * the thing it has no input for. If you cannot write that sentence, the
   * landmark is missing because the page is unfinished, and this is the wrong
   * place for it.
   */
  absentLandmarks?: Array<{
    /** The landmark's full class list, sorted and dot-joined — `signature()`'s key. */
    landmark: string
    desktop: number
    mobile: number
    reason: string
  }>
}

/**
 * A page is either not rebuilt yet, or it is rebuilt AND carries the landmark
 * counts it passed with.
 *
 * `baseline` is required on a "counter" page and forbidden on an "editorial"
 * one, so a page cannot be declared done without acquiring a regression floor
 * in the same edit (ruling F-R4). A later run finding fewer landmarks than the
 * baseline is a silent regression, not a pass.
 *
 * This is a type rather than a lint because `npm run fidelity` needs a running
 * server and so cannot join `npm test`. The manifest carries the weight
 * instead: marking a page done without a floor fails `tsc`, which every gate
 * already runs.
 */
export type FidelityPage =
  | (FidelityPageBase & { status: "editorial"; baseline?: never })
  | (FidelityPageBase & {
      status: "counter"
      baseline: { desktop: number; mobile: number }
    })

export const PAGES: FidelityPage[] = [
  {
    protoId: "overview",
    name: "Overview",
    protoRoute: "/dashboard",
    route: "/dashboard",
    query: "?range=d7&cmp=weekday",
    mobileRoute: "/m",
    status: "counter",
    report: true,
    baseline: { desktop: 76, mobile: 44 },
    absentLandmarks: [
      {
        landmark: "blt",
        desktop: 5,
        mobile: 4,
        reason:
          "The bullet meter. `Figure` draws it from a `Reference`, and " +
          "`referenceFor` in the Overview adapter returns undefined when no " +
          "target is published. This schema publishes two: " +
          "`Store.targetCogsPct` (food cost) and prime cost's trade ceiling " +
          "(PRIME_CEILING_PCT, ruling C-R1). Orders, avg ticket, labour and " +
          "marketplace fees are judged against nothing at all — the " +
          "prototype's bands for them are its own invention (`ords * 0.92`, " +
          "`$25.10-$26.40`), which is the figure judging itself. The desk " +
          "also loses the SPLH lead figure's meter for the same reason; the " +
          "phone does not draw that figure. Ruling Scan-R1.",
      },
      {
        landmark: "band",
        desktop: 2,
        mobile: 3,
        reason:
          "The flag words under a figure, which say what it was judged " +
          "against. `Figure` opens the band on `caption || reference`, so a " +
          "figure with neither has none — the same four unjudged figures as " +
          "`blt` above, minus the two the adapter gives a caption to on their " +
          "own (`Plan 28.5%` on food cost, `excludes grubhub` on fees). The " +
          "phone loses one more than the desk because `MStrip` follows " +
          "`mstrip()` and opens its band only inside the reference branch.",
      },
      {
        landmark: "hfloor",
        desktop: 1,
        mobile: 0,
        reason:
          "The floor meter under sales per labour hour. Nothing in this " +
          "schema publishes an SPLH floor: the prototype's `SPLH_FLOOR = " +
          "68.00` is its own number, and `SplhPoint.targetSplh` is the " +
          "median of the store's own weekday history — the figure judging " +
          "itself. `FloorMeter` mounts only when a floor is published, so " +
          "today it does not mount. The phone's head block carries one figure " +
          "and it is net sales, so this landmark is not on that surface at all.",
      },
      {
        landmark: "sp",
        desktop: 1,
        mobile: 0,
        reason:
          "The sparkline. `Figure` draws it from `reference.series`, so a " +
          "figure with no reference has no series to draw — downstream of the " +
          "same missing target as `blt`. The phone draws no sparklines at " +
          "all, by the prototype's own decision (`mstrip()`: the two charts " +
          "are directly beneath and vertical space is the scarce thing), so " +
          "neither side has one there and nothing is missing.",
      },
      {
        landmark: "moneyline",
        desktop: 1,
        mobile: 0,
        reason:
          "The invoices tile's fourth line, \"Does not reconcile\". " +
          "`Invoice` does carry `reviewReasons` — the `ReviewReason[]` " +
          "`src/lib/invoice-sanity.ts` writes when a header total does not " +
          "match its lines — but `getInvoiceSummary` neither selects nor " +
          "aggregates it, and no other existing function does. Three real " +
          "lines rather than four with one guessed. The phone drops the " +
          "invoices tile entirely, as the prototype's phone does.",
      },
    ],
  },
  { protoId: "ask", name: "Ask", protoRoute: "/dashboard/chat", route: "/dashboard/chat", status: "editorial" },
  {
    protoId: "decisions",
    name: "Needs you",
    protoRoute: "/dashboard/decisions",
    route: "/dashboard/decisions",
    // The middleware rewrites /dashboard/decisions to /m/decisions on a phone
    // UA. Stated so the rewrite reads as a rewrite and not as a page that
    // failed to load.
    mobileRoute: "/m/decisions",
    // NO `query`, and unlike Orders this page could not use one. Overview and
    // the P&L ask for `?range=d7&cmp=weekday` because their charts are day
    // series and our one-day default degrades them to a strip. This page has
    // no range at all: the week ahead is the week, not a window a reader
    // picks, so `PageHead` carries no `DateControl` (see the client's own
    // comment) and there is nothing for a range parameter to change. The
    // picker's seven cells are Monday to Sunday whatever is in the URL.
    status: "counter",
    report: true,
    // Measured, not chosen — the run of 2026-08-27, both surfaces.
    // Desk: 26 of the prototype's 30, 0 extra, 0 rendering differences, and
    // the four missing are the two `absentLandmarks` entries below.
    // Phone: 9 of 9, complete — landmark for landmark, 0 missing, 0 extra,
    // 0 rendering differences.
    baseline: { desktop: 26, mobile: 9 },
    absentLandmarks: [
      {
        landmark: "btn",
        desktop: 3,
        mobile: 0,
        reason:
          "Three buttons, and NEITHER is a gap in what the database can say " +
          "— both are deliberate subtractions, which is why they are written " +
          "here rather than left to look like unfinished work.\n" +
          "The first is the date control's \"Apply\". `DateControl` emits it " +
          "inside `.pagehead` whether or not its popover is open, so every " +
          "prototype page carrying a date bar carries a `.btn` at order 0 — " +
          "Orders renders one and matches. This page mounts NO `DateControl`: " +
          "the week ahead is the week, and a control offering to change it " +
          "would offer a window this page does not have. A control that " +
          "cannot change anything is the thing this codebase does not ship.\n" +
          "The other two are \"Add three shifts\" and \"Leave it\", the " +
          "prototype's `.btnrow` under the Saturday detail panel (line 4727). " +
          "Committing a shift needs a client action against `HarriShift` and " +
          "there is none; `buildDayDetail` is a server module and has no " +
          "handler to give, which is the same reason `buildDecisionQueue` " +
          "gives every queue item a LINK where the prototype writes " +
          "\"Commit\". Two buttons that did nothing would be worse than two " +
          "buttons that are not there.",
      },
      {
        landmark: "btnrow",
        desktop: 1,
        mobile: 0,
        reason:
          "The row that holds the two day-detail buttons above. It falls with " +
          "them and is counted separately because the gate counts landmarks, " +
          "not reasons. An empty `.btnrow` would be a wrapper drawn around " +
          "nothing — the same defect as the empty `.mlist` N-R18 removed from " +
          "the phone's alert list. The phone composes no button rows at all " +
          "(`P.decisions.phone` ends on a bare `.mbtn`, which carries no " +
          "landmark class on either side).",
      },
    ],
  },
  {
    protoId: "alerts",
    name: "Needs you",
    protoRoute: "/dashboard/alerts",
    route: "/dashboard/alerts",
    // The middleware rewrites /dashboard/alerts to /m/alerts on a phone UA.
    mobileRoute: "/m/alerts",
    // NO `query`, for a reason of its own. The inbox is a HORIZON — every
    // section reads the rows `getAlertInbox` loaded, which is
    // `occurredOn >= anomalyHorizon()` and not a range the URL sets. The one
    // chart is "Alerts opened", one bar per day of that horizon, and it draws
    // a `.ch` at the page's own default with no rendering differences. The
    // segment, the severities and the sources ARE in the URL; none of them is
    // a window, and the gate reads the page at its own default, which is
    // where the honest comparison is.
    status: "counter",
    report: true,
    // Measured, not chosen — the run of 2026-08-27.
    // Desk: 7 of the prototype's 8, 0 extra, 0 rendering differences; the one
    // missing is the `absentLandmarks` entry below.
    // Phone: 8 of 8, complete, 0 missing, 0 extra, 0 rendering differences —
    // after N-R18. Before it the phone matched 8 of 8 STRUCTURALLY and failed
    // the rendering pass with three differences, because the "Acknowledged"
    // list was scoped to `status = ACKNOWLEDGED` (0 rows in this database) and
    // an `.mlist` with no children has no grid track and no text. That is the
    // `.empty` constraint arriving from the other side: the shell-over-zero-
    // rows trick keeps the extra landmark out and leaves a blank panel, which
    // the structure pass cannot see and the rendering pass can.
    baseline: { desktop: 7, mobile: 8 },
    absentLandmarks: [
      {
        landmark: "btn",
        desktop: 1,
        mobile: 0,
        reason:
          "The date control's \"Apply\", and the same deliberate subtraction " +
          "as the first of the decisions page's three. `DateControl` emits it " +
          "inside `.pagehead`, and this page mounts no `DateControl`: the " +
          "inbox is the horizon `anomalyHorizon()` sets, so `PageHead` NAMES " +
          "the window (\"last 30 days\") rather than offering to change it. " +
          "The controls this page does have — the segment, the severity and " +
          "source toggles, the search box — are `.seg` and `.tog`, which the " +
          "prototype draws too and which are matched. The phone has no page " +
          "head furniture at all on either side.",
      },
    ],
  },
  {
    protoId: "orders",
    name: "Orders",
    protoRoute: "/dashboard/orders",
    route: "/dashboard/orders",
    // The middleware rewrites /dashboard/orders to /m/orders on a phone UA.
    // Stated so the rewrite is reported as a rewrite and not as a page that
    // failed to load.
    mobileRoute: "/m/orders",
    // NO `query`, deliberately — and this is the first Counter page that needs
    // none. Overview and the P&L ask for `?range=d7&cmp=weekday` because their
    // charts are day series and our one-day default degrades them to a strip,
    // which the gate would read as a difference. This page's only chart is
    // `Orders by hour`: 24 hourly buckets whatever the range, and its band is
    // the last four same-weekdays, which the range does not choose either. So
    // the page draws a `.ch` at its OWN default and the honest comparison is
    // the one made there.
    status: "counter",
    report: true,
    // Measured, not chosen. Desk 10 of the prototype's 10; phone 5 of 5. Both
    // surfaces match the prototype landmark for landmark, with 0 missing, 0
    // extra and 0 rendering differences.
    baseline: { desktop: 10, mobile: 5 },
    // No `absentLandmarks`, and that is a finding rather than an omission.
    // The plan expected `.blt` / `.band` / `.sp` to be owed under every strip
    // cell, on the reasoning that nothing in `prisma/schema.prisma` publishes
    // a per-order target. The reasoning is right and the conclusion was wrong:
    // the PROTOTYPE draws no meter here either. `P.orders.desk()` (line 4854)
    // passes three- and four-element cells to `strip()` — label, value, delta,
    // tone — and `strip()` opens a bullet, a band and a sparkline only from a
    // reference it was not given. Neither side has one, so nothing is missing
    // and an allowance would have failed as STALE the first time it ran.
  },
  {
    protoId: "order",
    name: "An order",
    protoRoute: "/dashboard/orders/4821",
    // #4821 is the prototype's own invented order. Ours has to be a REAL one,
    // and which one is a decision the gate can see, so it is written down.
    //
    // `3D4B7815` — DoorDash, Hollywood, 12 Jul 2026, nine lines, $35.19
    // charged with $8.80 of commission recorded against it (25.0%, the rate
    // every DoorDash sample lands on) and exactly ONE line with no recipe
    // behind it.
    //
    // The last of those is why it, and not another order. The prototype's
    // #4821 carries one uncosted modifier and therefore a "Needs you" section
    // with a one-item queue. `buildNeedsYou` returns `empty("all_clear")` for
    // an order with nothing to fix, and `Empty` renders `.empty` in place of
    // the queue — an EXTRA landmark, which ruling F-R8 never forgives and no
    // `absentLandmarks` entry can express. So an order with a clean bill of
    // lines cannot be the subject here: it would compare our page in its empty
    // state against the prototype's in its full one, and the difference would
    // be about the row we picked rather than about the design.
    //
    // Measured over the whole account: 19,911 orders of 20,000 have every line
    // costed, 87 have exactly one that is not, 2 have two. So this shape is
    // rare, and it is the shape the design was drawn for. If someone maps that
    // sku the queue empties and this gate goes red with an extra `.empty` —
    // which is the correct alarm, and the fix is another id from the same 87.
    route: "/dashboard/orders/4551abf7-d5b1-484f-9eef-3e25cdf1a1fe",
    mobileRoute: "/m/orders/4551abf7-d5b1-484f-9eef-3e25cdf1a1fe",
    // `nodate: true` in the prototype (line 6569) and no window on our side
    // either: an order happened at one instant, so there is no range to ask
    // for.
    status: "counter",
    report: true,
    // Measured, not chosen. Desk 20 of the prototype's 20; phone 12 of 12.
    // Both surfaces match landmark for landmark, 0 missing, 0 extra, 0
    // rendering differences.
    baseline: { desktop: 20, mobile: 12 },
    // No `absentLandmarks`, on the same finding as the list above plus two of
    // its own:
    //
    //   - the prototype's own `strip()` call at line 6574 passes no reference,
    //     so there is no `.blt`, no `.band` and no `.sp` on EITHER side;
    //   - the item rows link to `catalogitem`, which is not rebuilt, so
    //     `OrderItemRow` carries no href — but a row's link is an `<a>` inside
    //     `.tbl` and carries no landmark class, so the gate sees no difference
    //     and there is nothing to record. It stays a real gap in the page and
    //     a false one to write here.
    //
    // The Timeline and Platform panels print fewer ROWS than the prototype
    // (nothing in this schema records accepted/ready/collected times, or a
    // payout id and date). `.kv` is the landmark and both of them render, so
    // that is not an absence either — it is two shorter lists.
  },
  {
    protoId: "analytics",
    name: "Analytics",
    protoRoute: "/dashboard/analytics",
    route: "/dashboard/analytics",
    // Same window as Overview and the P&L, and for the same reason: a mix
    // drawn over one day has no first and last third to compare, and the gate
    // would report that agreement as a difference.
    query: "?range=d7&cmp=weekday",
    mobileRoute: "/m/analytics",
    // Reporting first, gating second — the order Overview and the P&L went in.
    // A baseline invented before it is measured is a number nobody can defend.
    report: true,
    status: "editorial",
  },
  {
    protoId: "pnl",
    name: "P&L",
    protoRoute: "/dashboard/pnl",
    route: "/dashboard/pnl",
    // The window the prototype is in — same as Overview's, and for the same
    // reason (see `query` above). Our default is one day; a statement drawn
    // over one day degrades every series on it, and the gate would report that
    // agreement as a difference.
    query: "?range=d7&cmp=weekday",
    // The middleware rewrites /dashboard/pnl to /m/pnl on a phone UA, so the
    // mobile projects land there. Stated so a rewrite is not reported as a
    // page that failed to load. The phone SURFACE is still editorial — that is
    // Task 5 — and its report says so in landmark counts.
    mobileRoute: "/m/pnl",
    // Rebuilt on Counter across Phase C tasks 4 and 5, measured from those
    // commits while still `editorial`, and GATED here. Reporting first and
    // gating second is the order Overview went in: a baseline invented before
    // it was measured is a number nobody can defend. `report` stays on so the
    // committed `docs/counter/fidelity/pnl.md` keeps being regenerated from
    // what the gate actually measured.
    report: true,
    status: "counter",
    // Measured, not chosen. Desk: 43 of the prototype's 51, 0 extra, 0
    // rendering differences. Phone: 21 of 21, complete — the first surface in
    // this project that matches the prototype landmark for landmark.
    baseline: { desktop: 43, mobile: 21 },
    absentLandmarks: [
      {
        landmark: "blt",
        desktop: 1,
        mobile: 0,
        reason:
          "The LABOUR bullet, and only that one — prime cost and food both " +
          "draw theirs. `Figure` opens a bullet from a judged `Reference`, " +
          "and `referenceFor` in `adapters/pnl.ts` has nothing to judge " +
          "labour against: `loadStripTargets` returns `labor: null` because " +
          "no column in `prisma/schema.prisma` publishes a labour band " +
          "(`Store.targetCogsPct` is the schema's ONE published reference, " +
          "and `Store.fixedMonthlyLabor` is a budget in dollars, not a " +
          "percent of sales). The prototype's 23.9–26.2%-plus-salaried is its " +
          "own invention (line 5276), which is the figure judging itself. " +
          "The labour cell is NOT unwired: it carries a `Reference` with the " +
          "eight-week trajectory, so its `.sp` and `.band` both land — the " +
          "bullet is the one part with no input. Ruling Scan-R1. The phone " +
          "draws two cells (bottom line, prime cost) and labour is not one of " +
          "them, so nothing is missing there.",
      },
      {
        landmark: "gap",
        desktop: 1,
        mobile: 0,
        reason:
          "The food-cause bar. `GapBar` names the causes of a food overshoot " +
          "in POINTS, and `getPnlSections` returns `foodCause` as " +
          "`not_computed`: nothing in this schema attributes points of the " +
          "food line to one ingredient. That needs each ingredient's SHARE of " +
          "food spend over the range beside its own price move, and the price " +
          "monitor publishes the moves without the shares — there is no " +
          "`src/lib/**` function that computes the pair, checked rather than " +
          "assumed. A bar whose only segment is \"everything else\" would add " +
          "a picture of an explanation and no explanation. The plan-versus-" +
          "actual half of the same fact IS on the page, in the strip's food " +
          "cell. The phone composes no food-cause section at all " +
          "(`P.pnl.phone()` has three sections and this is not one), so " +
          "neither side has it there.",
      },
      {
        landmark: "btnrow",
        desktop: 2,
        mobile: 0,
        reason:
          "The action rows of the two sections that are `not_computed` — the " +
          "food-cause section's (\"Ask why\" / \"Open cost of goods\") and the " +
          "trust panel's (\"Post the N invoices\"). Both are children of a " +
          "section BODY, and `Section` renders `Owed` in place of the body " +
          "when the data is `not_computed`; a page may not branch on a " +
          "section's status (`npm run tokens` fails the build on it), so " +
          "there is no arm in which the buttons render beside an absent " +
          "answer. `Owed` carries no actions by design, for the same reason " +
          "`Empty` drops the prototype's `.btn`: this codebase does not ship " +
          "a control that does nothing, and \"Post the 6 invoices\" cannot be " +
          "written without the count, which is the very query that is " +
          "missing. The by-store section's `.btnrow` is present and matched. " +
          "The phone has none of these sections.",
      },
      {
        landmark: "btn",
        desktop: 4,
        mobile: 0,
        reason:
          "Three of these are the buttons inside the two `.btnrow`s above and " +
          "fall with them — same cause, counted separately because the gate " +
          "counts landmarks, not reasons. The FOURTH is a deliberate " +
          "subtraction rather than an absence: the prototype's by-store row " +
          "offers \"Open a store P&L\" pointing at its `pnlstore` page, which " +
          "on this rebuild is the page the reader is already on, scoped by " +
          "`?store=` — `/dashboard/pnl/[storeId]` is a 308 shim to exactly " +
          "that URL, and the rail's store switcher is the gesture. A button " +
          "whose destination is the current page is a control that does " +
          "nothing. \"Fill in a store file\" survives and is matched. The " +
          "phone composes no button rows.",
      },
    ],
  },
  { protoId: "cogs", name: "COGS", protoRoute: "/dashboard/cogs", route: "/dashboard/cogs", status: "editorial" },
  { protoId: "menu", name: "Menu profit", protoRoute: "/dashboard/menu-profit", route: "/dashboard/menu-profit", status: "editorial" },
  { protoId: "labor", name: "Labor", protoRoute: "/dashboard/labor", route: "/dashboard/labor", status: "editorial" },
  { protoId: "pnlstore", name: "P&L", protoRoute: "/dashboard/pnl/hollywood", route: "/dashboard/pnl/hollywood", status: "editorial" },
  { protoId: "menuhub", name: "Menu profit", protoRoute: "/dashboard/menu", route: "/dashboard/menu", status: "editorial" },
  { protoId: "catalog", name: "Menu profit", protoRoute: "/dashboard/menu/catalog", route: "/dashboard/menu/catalog", status: "editorial" },
  { protoId: "catalogitem", name: "A menu item", protoRoute: "/dashboard/menu/catalog/neddy-burger", route: "/dashboard/menu/catalog/neddy-burger", status: "editorial" },
  { protoId: "recipes", name: "Recipes", protoRoute: "/dashboard/recipes", route: "/dashboard/recipes", status: "editorial" },
  { protoId: "recipe", name: "Recipe", protoRoute: "/dashboard/recipes/double-slider", route: "/dashboard/recipes/double-slider", status: "editorial" },
  { protoId: "productmix", name: "Menu profit", protoRoute: "/dashboard/product-mix", route: "/dashboard/product-mix", status: "editorial" },
  { protoId: "usage", name: "COGS", protoRoute: "/dashboard/operations/product-usage", route: "/dashboard/operations/product-usage", status: "editorial" },
  { protoId: "operations", name: "Operations", protoRoute: "/dashboard/operations", route: "/dashboard/operations", status: "editorial" },
  { protoId: "invoices", name: "Invoices", protoRoute: "/dashboard/invoices", route: "/dashboard/invoices", status: "editorial" },
  { protoId: "invoice", name: "An invoice", protoRoute: "/dashboard/invoices/I28517", route: "/dashboard/invoices/I28517", status: "editorial" },
  { protoId: "inventory", name: "Inventory", protoRoute: "/dashboard/operations/inventory", route: "/dashboard/operations/inventory", status: "editorial" },
  { protoId: "countnew", name: "Inventory", protoRoute: "/dashboard/operations/inventory/count/new", route: "/dashboard/operations/inventory/count/new", status: "editorial" },
  { protoId: "counts", name: "Inventory", protoRoute: "/dashboard/operations/inventory/counts", route: "/dashboard/operations/inventory/counts", status: "editorial" },
  { protoId: "countsession", name: "A count", protoRoute: "/dashboard/operations/inventory/counts/aug-14", route: "/dashboard/operations/inventory/counts/aug-14", status: "editorial" },
  { protoId: "ingredients", name: "Ingredients", protoRoute: "/dashboard/ingredients", route: "/dashboard/ingredients", status: "editorial" },
  { protoId: "ingredient", name: "An ingredient", protoRoute: "/dashboard/ingredients/ground-beef-80-20", route: "/dashboard/ingredients/ground-beef-80-20", status: "editorial" },
  { protoId: "prices", name: "Ingredients", protoRoute: "/dashboard/ingredients/prices", route: "/dashboard/ingredients/prices", status: "editorial" },
  { protoId: "vendors", name: "Vendors", protoRoute: "/dashboard/operations/vendors", route: "/dashboard/operations/vendors", status: "editorial" },
  { protoId: "vendor", name: "A vendor", protoRoute: "/dashboard/operations/vendors/ifs-produce", route: "/dashboard/operations/vendors/ifs-produce", status: "editorial" },
  { protoId: "packaging", name: "Vendors", protoRoute: "/dashboard/operations/packaging", route: "/dashboard/operations/packaging", status: "editorial" },
  { protoId: "stores", name: "Stores", protoRoute: "/dashboard/stores", route: "/dashboard/stores", status: "editorial" },
  { protoId: "storecosts", name: "Stores", protoRoute: "/dashboard/stores/hollywood", route: "/dashboard/stores/hollywood", status: "editorial" },
  { protoId: "storeedit", name: "Stores", protoRoute: "/dashboard/stores/new", route: "/dashboard/stores/new", status: "editorial" },
  { protoId: "settings", name: "Settings", protoRoute: "/dashboard/settings", route: "/dashboard/settings", status: "editorial" },
  { protoId: "more", name: "More (phone)", protoRoute: "/m/more", route: "/m/more", status: "editorial" },
  { protoId: "monitoring", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring", route: "/dashboard/admin/monitoring", status: "editorial" },
  { protoId: "monml", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ml", route: "/dashboard/admin/monitoring/ml", status: "editorial" },
  { protoId: "monpeople", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/people", route: "/dashboard/admin/monitoring/people", status: "editorial" },
  {
    protoId: "analyticsstore",
    name: "Analytics",
    protoRoute: "/dashboard/analytics/hollywood",
    // Hollywood's id is a cuid, not the prototype's slug. It is the only store
    // on this account that has ever traded.
    route: "/dashboard/analytics/cmexd4zia0001jr04ljkdt9na",
    query: "?range=d7&cmp=weekday",
    mobileRoute: "/m/analytics/cmexd4zia0001jr04ljkdt9na",
    report: true,
    status: "editorial",
  },
  { protoId: "laborstore", name: "Labor", protoRoute: "/dashboard/labor/hollywood", route: "/dashboard/labor/hollywood", status: "editorial" },
  { protoId: "cogsstore", name: "COGS", protoRoute: "/dashboard/cogs/hollywood", route: "/dashboard/cogs/hollywood", status: "editorial" },
  { protoId: "moninfra", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/infrastructure", route: "/dashboard/admin/monitoring/infrastructure", status: "editorial" },
  { protoId: "moncosts", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/costs", route: "/dashboard/admin/monitoring/costs", status: "editorial" },
  { protoId: "moncache", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/cache", route: "/dashboard/admin/monitoring/cache", status: "editorial" },
  { protoId: "monactivity", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/activity", route: "/dashboard/admin/monitoring/activity", status: "editorial" },
  { protoId: "moningredients", name: "Monitoring", protoRoute: "/dashboard/admin/monitoring/ingredient-audit", route: "/dashboard/admin/monitoring/ingredient-audit", status: "editorial" },
  { protoId: "login", name: "Login", protoRoute: "/login", route: "/login", status: "editorial" },
  { protoId: "signup", name: "Accept invite", protoRoute: "/signup/[token]", route: "/signup/[token]", status: "editorial" },
  { protoId: "shutdown", name: "Shutdown", protoRoute: "/shutdown", route: "/shutdown", status: "editorial" },
  { protoId: "notfound", name: "Not found", protoRoute: "/dashboard/not-found", route: "/dashboard/not-found", status: "editorial" },
  { protoId: "forbidden", name: "No access", protoRoute: "403", route: "403", status: "editorial" },
]

/** The absence budget for one surface, as `applyAbsenceAllowances` wants it. */
export function absenceBudget(
  entry: FidelityPage,
  surface: "desk" | "phone",
): Record<string, number> {
  const out: Record<string, number> = {}
  for (const a of entry.absentLandmarks ?? []) {
    const n = surface === "desk" ? a.desktop : a.mobile
    if (n > 0) out[a.landmark] = n
  }
  return out
}

export function pageById(protoId: string): FidelityPage {
  const p = PAGES.find((x) => x.protoId === protoId)
  if (!p) throw new Error(`No fidelity manifest entry for "${protoId}"`)
  return p
}

