import { Prisma } from "@/generated/prisma/client"
import { prisma } from "@/lib/prisma"
import { logger } from "@/lib/logger"
import type { ChatToolName } from "./tools"

/**
 * WHEN THE NUMBERS IN AN ANSWER WERE LAST REFRESHED.
 *
 * ## Why
 *
 * "No answer says when its data is from" is one of the four pieces of debt the
 * Ask proposal names, and it is the one that quietly costs the most: Otter
 * backfills closed windows, so a dollar figure moves within hours of being
 * read. An answer that carries the tool names it read, and not the moment
 * those tables were last written, cannot be checked and cannot be cached —
 * the answer cache keys on exactly this.
 *
 * ## What it measures
 *
 * The freshness of the DATA, not of the request. `MAX(syncedAt)` on the table
 * behind the tool, which moves when the sync writes and stands still when it
 * does not — so a stalled cron shows as an old `asOf` rather than a fresh one.
 * That is the same reading `src/lib/monitoring/staleness.ts` takes for the
 * staleness cron; this is the per-tool half of it, and the two must not
 * disagree about what a table's freshness column is.
 *
 * A tool with no entry in `TOOL_AS_OF` reports no `asOf`, and that is honest
 * rather than missing: `listStores` and `describeSchema` read structure, and
 * `simulatePriceChange` computes rather than reads. The proposal's rule for
 * the cache follows from it — a tool without an `asOf` is excluded from
 * caching until it has one.
 */

export type AsOfSource =
  | "otterDaily"
  | "otterHourly"
  | "otterOrders"
  | "invoices"
  | "cogs"
  | "forecasts"
  | "labor"

/**
 * Table and freshness column per source. Module constants, never request
 * input — which is what makes the `Prisma.raw` interpolation below safe, the
 * same argument the staleness cron makes for the same query shape.
 */
const SOURCE_TABLES: Record<AsOfSource, { table: string; column: string }> = {
  otterDaily: { table: "OtterDailySummary", column: "syncedAt" },
  otterHourly: { table: "OtterHourlySummary", column: "updatedAt" },
  otterOrders: { table: "OtterOrder", column: "syncedAt" },
  invoices: { table: "Invoice", column: "updatedAt" },
  cogs: { table: "DailyCogsItem", column: "computedAt" },
  forecasts: { table: "ForecastDailyRevenue", column: "generatedAt" },
  labor: { table: "HarriDailyLabor", column: "syncedAt" },
}

/**
 * Which table's freshness a tool's answer actually depends on.
 *
 * Read as: "if this number were wrong because data was stale, which sync
 * would be the reason?" `getCogsByItem` reads the COGS sweep's output, so it
 * is `cogs` and not `otterDaily`, even though the sweep is downstream of
 * Otter — naming the nearest table is what makes the stamp checkable.
 *
 * Absent on purpose: `listStores`, `describeSchema`, `fileReturn` (structure
 * and presentation, no figures), `simulatePriceChange` and
 * `getMenuItemElasticity` (a model over data already stamped by its inputs),
 * and the menu/recipe/ingredient catalogue tools, which are edited by hand
 * rather than synced and so have no refresh moment to report.
 */
export const TOOL_AS_OF: Partial<Record<ChatToolName, AsOfSource>> = {
  // Sales — the daily rollup, except the hour-of-day view.
  getDailySales: "otterDaily",
  compareSales: "otterDaily",
  getPlatformBreakdown: "otterDaily",
  getStoreBreakdown: "otterDaily",
  getChannelMix: "otterDaily",
  getHourlyTrend: "otterHourly",
  // Order-level drilldown reads the order rows themselves.
  getOrderById: "otterOrders",
  listOrdersByDay: "otterOrders",
  getOrderItemFrequency: "otterOrders",
  getRefunds: "otterOrders",
  // Invoices and anything priced off them.
  searchInvoices: "invoices",
  sumInvoiceLines: "invoices",
  getTopInvoices: "invoices",
  getInvoiceSpend: "invoices",
  getInvoiceById: "invoices",
  getIngredientPrices: "invoices",
  getIngredientPrice: "invoices",
  getIngredientPriceHistory: "invoices",
  compareVendorPrices: "invoices",
  // The COGS sweep's own output.
  getCogsByItem: "cogs",
  getMenuMargin: "cogs",
  // P&L stands on the daily rollup plus the sweep; the rollup is the one that
  // moves on a backfill, so it is the honest stamp.
  getPnlSummary: "otterDaily",
  searchPnlHistory: "otterDaily",
  getOperationalCosts: "otterDaily",
  getTopMenuItems: "otterDaily",
  // Labour.
  getLaborStaffingForecast: "labor",
  // Everything generated by the ML pipeline.
  getRevenueForecast: "forecasts",
  getMenuItemForecast: "forecasts",
  getFoodCostForecast: "forecasts",
  getCashPositionForecast: "forecasts",
  getLostSales: "forecasts",
  getPromoRoi: "forecasts",
  getLaunchTrajectory: "forecasts",
  getMenuEngineering: "forecasts",
  getVendorReliability: "forecasts",
  getWasteRootCauses: "forecasts",
}

/**
 * One MAX() per source, memoised for the life of a turn and a little beyond.
 *
 * The syncs run every four hours at best, so a reading minutes old is the
 * same reading. The TTL exists to keep several tools in one turn — and the
 * turns behind one reader — off the same seven queries.
 */
const TTL_MS = 5 * 60_000
const cache = new Map<AsOfSource, { at: number; value: Date | null }>()
const inflight = new Map<AsOfSource, Promise<Date | null>>()

async function readSource(source: AsOfSource): Promise<Date | null> {
  const hit = cache.get(source)
  if (hit && Date.now() - hit.at < TTL_MS) return hit.value

  const existing = inflight.get(source)
  if (existing) return existing

  const { table, column } = SOURCE_TABLES[source]
  const p = (async () => {
    try {
      const rows = await prisma.$queryRaw<{ max: Date | null }[]>(
        Prisma.sql`SELECT MAX(${Prisma.raw(`"${column}"`)}) AS max FROM ${Prisma.raw(`"${table}"`)}`,
      )
      const value = rows[0]?.max ?? null
      cache.set(source, { at: Date.now(), value })
      return value
    } catch (err) {
      // A missing stamp is a smaller problem than a failed answer, so this
      // never throws into the turn.
      logger.warn(`[chat] asOf read failed for ${source}`, err)
      return null
    } finally {
      inflight.delete(source)
    }
  })()
  inflight.set(source, p)
  return p
}

/**
 * The NEWEST stamp across a set of tools — the answer cache's key material.
 *
 * Newest rather than oldest on purpose: the question the key has to answer is
 * "has anything these tools read been rewritten since?", and any one table
 * moving is enough to invalidate. An oldest-wins key would hold a stale answer
 * for as long as the least-synced table stood still.
 */
export async function maxAsOfForTools(toolNames: readonly string[]): Promise<string | null> {
  const sources = new Set<AsOfSource>()
  for (const n of toolNames) {
    const s = TOOL_AS_OF[n as ChatToolName]
    if (s) sources.add(s)
  }
  if (sources.size === 0) return null
  const reads = await Promise.all([...sources].map(readSource))
  const newest = reads.reduce<Date | null>(
    (acc, d) => (d && (!acc || d > acc) ? d : acc),
    null,
  )
  return newest ? newest.toISOString() : null
}

/**
 * Whether every tool in a set reports a stamp.
 *
 * The proposal's caching rule, enforced: a tool without an `asOf` has no
 * moment that could invalidate it, so an answer that read one cannot be
 * safely cached at any TTL. Used at store time against the tools the turn
 * ACTUALLY read, not the ones it was offered.
 */
export function everyToolStamped(toolNames: readonly string[]): boolean {
  return toolNames.every(
    (n) => READS_NO_FIGURES.has(n as ChatToolName) || Boolean(TOOL_AS_OF[n as ChatToolName]),
  )
}

/**
 * Tools that read no data at all, so they cannot go stale and must not block
 * an answer from being stored.
 *
 * `fileReturn` is the one that matters: it is how the model FILES the answer
 * (verdict, figures, follow-ups), and it is called on nearly every good turn.
 * Left out of `TOOL_AS_OF` on purpose (above) and checked here as if it were
 * stamped, because before this the two rules met head-on — every answer that
 * filed a return "read an unstamped tool", the write guard in the chat route
 * refused it, and the answer cache held zero entries after a day of turns.
 * The same question, asked again, ran the model every time.
 *
 * `listStores` and `describeSchema` stay out: a store can be added, and an
 * answer that read the store list has a fact that can change without a sync.
 */
const READS_NO_FIGURES: ReadonlySet<ChatToolName> = new Set<ChatToolName>(["fileReturn"])

/** The freshness stamp for one tool, or null when it reports none. */
export async function asOfForTool(toolName: string): Promise<string | null> {
  const source = TOOL_AS_OF[toolName as ChatToolName]
  if (!source) return null
  const at = await readSource(source)
  return at ? at.toISOString() : null
}
